/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import BUS.Users_BUS;
import DTO.Users_DTO;
import javax.swing.*;
/**
 *
 * @author trita
 */
public class Frame_DangKy extends javax.swing.JFrame {
    Users_BUS usBUS = new Users_BUS();
    /**
     * Creates new form Frame_DangKy
     */
    public Frame_DangKy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton_DangKy = new javax.swing.JButton();
        jTextField_TenTaiKhoan = new javax.swing.JTextField();
        jPasswordField_MatKhau = new javax.swing.JPasswordField();
        jPasswordField_NhapLaiMatKhau = new javax.swing.JPasswordField();
        jButton_TroLaiDangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký");
        setLocation(new java.awt.Point(400, 250));
        setMinimumSize(new java.awt.Dimension(628, 320));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SIGN UP");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu");

        jButton_DangKy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_DangKy.setText("Đăng ký");
        jButton_DangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DangKyActionPerformed(evt);
            }
        });

        jTextField_TenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPasswordField_MatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField_MatKhau.setText("jPasswordField1");

        jPasswordField_NhapLaiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField_NhapLaiMatKhau.setText("jPasswordField2");

        jButton_TroLaiDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_TroLaiDangNhap.setText("Trở lại đăng nhập");
        jButton_TroLaiDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TroLaiDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField_TenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jPasswordField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17)
                        .addComponent(jPasswordField_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton_TroLaiDangNhap)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_TenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(jPasswordField_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jPasswordField_NhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_TroLaiDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_DangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DangKyActionPerformed
        try{
            if(jTextField_TenTaiKhoan.getText().trim().equals("")||
                    jPasswordField_MatKhau.getText().trim().equals("")||
                    jPasswordField_NhapLaiMatKhau.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else{
                Users_DTO us=new Users_DTO();
                us.setUsername(jTextField_TenTaiKhoan.getText());
                us.setPassword(jPasswordField_MatKhau.getText());
                String confirm = jPasswordField_NhapLaiMatKhau.getText();
                if(confirm.equals(us.getPassword())){
                    if(usBUS.hasUser(us)){
                        JOptionPane.showMessageDialog(this,"Tài khoản đã tồn tại !");
                    }
                    else{
                        JOptionPane.showMessageDialog(this,usBUS.addUser(us));
                        Frame_DangNhap dn = new Frame_DangNhap();
                        dn.setVisible(true);
                        this.dispose();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this,"Nhập lại mật khẩu không đúng");
                }
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }     
    }//GEN-LAST:event_jButton_DangKyActionPerformed

    private void jButton_TroLaiDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TroLaiDangNhapActionPerformed
        Frame_DangNhap dn = new Frame_DangNhap();
        dn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_TroLaiDangNhapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DangKy;
    private javax.swing.JButton jButton_TroLaiDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField_MatKhau;
    private javax.swing.JPasswordField jPasswordField_NhapLaiMatKhau;
    private javax.swing.JTextField jTextField_TenTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
