package GUI;
import DTO.*;
import BUS.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author haile
 */
public class Panel_Kho extends javax.swing.JPanel {
    KhoHang_BUS kBUS = new KhoHang_BUS();
    SanPham_BUS spBUS = new SanPham_BUS();
    Date date = new Date();
    
    /**
     * Creates new form Panel_Kho
     */
    public Panel_Kho() {
        initComponents();
        getKhoHangList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_BaoCaoXuatNhapKho = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jFrame_TimKiem = new javax.swing.JFrame();
        jFrame_ThemDuLieuTonKho = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_ThemTonKho_TenSP = new javax.swing.JComboBox<>();
        jTextField_ThemTonKho_TimKiem = new javax.swing.JTextField();
        jTextField_ThemTonKho_MaSP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_ThemTonKho_Size = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_ThemTonKho_SL = new javax.swing.JTextField();
        jButton_ThemTonKho_Huy = new javax.swing.JButton();
        jButton_ThemTonKho_Luu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Kho = new javax.swing.JTable();
        jLabel_maSP = new javax.swing.JLabel();
        jLabel_tenSP = new javax.swing.JLabel();
        jLabel_SL = new javax.swing.JLabel();
        jLabel_giatien = new javax.swing.JLabel();
        jLabel_capnhat = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_MaSanPham = new javax.swing.JTextField();
        jTextField_TenSanPham = new javax.swing.JTextField();
        jTextField_SoLuong = new javax.swing.JTextField();
        jTextField_GiaTien = new javax.swing.JTextField();
        jTextField_ThoiGianCapNhat = new javax.swing.JTextField();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_BaoCaoXuatNhapKho = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Size = new javax.swing.JTextField();
        jButton_ThemTonKho = new javax.swing.JButton();

        jFrame_BaoCaoXuatNhapKho.setMinimumSize(new java.awt.Dimension(1027, 478));
        jFrame_BaoCaoXuatNhapKho.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tháng");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Năm");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên hàng hóa", "Đơn vị tính", "Số lượng", "Thành tiền", "Thời gian cập nhật", "Số lượng", "Thành tiền", "Thời gian nhập", "Đơn giá xuất kho", "Số lượng", "Thành tiền", "Thời gian xuất", "Số lượng", "Thành tiền", "Thời gian cập nhật"
            }
        ));
        jTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable2.setRowSelectionAllowed(false);
        jTable2.setShowGrid(true);
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jFrame_BaoCaoXuatNhapKhoLayout = new javax.swing.GroupLayout(jFrame_BaoCaoXuatNhapKho.getContentPane());
        jFrame_BaoCaoXuatNhapKho.getContentPane().setLayout(jFrame_BaoCaoXuatNhapKhoLayout);
        jFrame_BaoCaoXuatNhapKhoLayout.setHorizontalGroup(
            jFrame_BaoCaoXuatNhapKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_BaoCaoXuatNhapKhoLayout.createSequentialGroup()
                .addGroup(jFrame_BaoCaoXuatNhapKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_BaoCaoXuatNhapKhoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame_BaoCaoXuatNhapKhoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jFrame_BaoCaoXuatNhapKhoLayout.setVerticalGroup(
            jFrame_BaoCaoXuatNhapKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_BaoCaoXuatNhapKhoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jFrame_BaoCaoXuatNhapKhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_TimKiemLayout = new javax.swing.GroupLayout(jFrame_TimKiem.getContentPane());
        jFrame_TimKiem.getContentPane().setLayout(jFrame_TimKiemLayout);
        jFrame_TimKiemLayout.setHorizontalGroup(
            jFrame_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame_TimKiemLayout.setVerticalGroup(
            jFrame_TimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jFrame_ThemDuLieuTonKho.setMinimumSize(new java.awt.Dimension(684, 431));
        jFrame_ThemDuLieuTonKho.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame_ThemDuLieuTonKhoWindowClosing(evt);
            }
        });
        jFrame_ThemDuLieuTonKho.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tìm kiếm");
        jFrame_ThemDuLieuTonKho.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 79, 89, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã sản phẩm");
        jFrame_ThemDuLieuTonKho.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 180, 89, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên sản phẩm");
        jFrame_ThemDuLieuTonKho.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 131, -1, -1));

        jComboBox_ThemTonKho_TenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_ThemTonKho_TenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_ThemTonKho_TenSPActionPerformed(evt);
            }
        });
        jFrame_ThemDuLieuTonKho.getContentPane().add(jComboBox_ThemTonKho_TenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 128, 464, -1));

        jTextField_ThemTonKho_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_ThemTonKho_TimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField_ThemTonKho_TimKiemCaretUpdate(evt);
            }
        });
        jFrame_ThemDuLieuTonKho.getContentPane().add(jTextField_ThemTonKho_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 79, 464, -1));

        jTextField_ThemTonKho_MaSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFrame_ThemDuLieuTonKho.getContentPane().add(jTextField_ThemTonKho_MaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 177, 464, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Size");
        jFrame_ThemDuLieuTonKho.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 233, 89, -1));

        jTextField_ThemTonKho_Size.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFrame_ThemDuLieuTonKho.getContentPane().add(jTextField_ThemTonKho_Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 227, 464, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số lượng");
        jFrame_ThemDuLieuTonKho.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 286, 89, -1));

        jTextField_ThemTonKho_SL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFrame_ThemDuLieuTonKho.getContentPane().add(jTextField_ThemTonKho_SL, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 280, 464, -1));

        jButton_ThemTonKho_Huy.setText("Hủy");
        jButton_ThemTonKho_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemTonKho_HuyActionPerformed(evt);
            }
        });
        jFrame_ThemDuLieuTonKho.getContentPane().add(jButton_ThemTonKho_Huy, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 351, 106, 40));

        jButton_ThemTonKho_Luu.setText("Lưu");
        jButton_ThemTonKho_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemTonKho_LuuActionPerformed(evt);
            }
        });
        jFrame_ThemDuLieuTonKho.getContentPane().add(jButton_ThemTonKho_Luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 351, 105, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Ngày cập nhật");
        jFrame_ThemDuLieuTonKho.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 19, 100, -1));

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("KHO");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1259, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách tồn kho sản phẩm");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 42, -1, -1));

        jTable_Kho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm ", "Tên sản phẩm", "Size", "Số lượng", "Giá tiền", "Thời gian cập nhật"
            }
        ));
        jTable_Kho.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable_Kho.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_Kho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_KhoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Kho);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 79, 757, 480));

        jLabel_maSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_maSP.setText("Mã sản phẩm");
        add(jLabel_maSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(797, 92, -1, -1));

        jLabel_tenSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_tenSP.setText("Tên sản phẩm");
        add(jLabel_tenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 138, -1, -1));

        jLabel_SL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_SL.setText("Số lượng");
        add(jLabel_SL, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 234, 86, -1));

        jLabel_giatien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_giatien.setText("Giá tiền");
        add(jLabel_giatien, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 283, 86, -1));

        jLabel_capnhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_capnhat.setText("Thời gian cập");
        add(jLabel_capnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 334, 89, 17));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("nhật lần cuối");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 361, -1, -1));

        jTextField_MaSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_MaSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 89, 320, -1));

        jTextField_TenSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_TenSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 135, 320, -1));

        jTextField_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 231, 320, -1));

        jTextField_GiaTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_GiaTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 280, 320, -1));

        jTextField_ThoiGianCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_ThoiGianCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 320, -1));

        jButton_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_refresh_100px.png"))); // NOI18N
        jButton_LamMoi.setText("Làm mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 200, 70));

        jButton_add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_add.setText("Thêm Sản phẩm mới");
        jButton_add.setEnabled(false);
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });
        add(jButton_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 330, 50));

        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_edit_100px.png"))); // NOI18N
        jButton_Sua.setText("Sửa dữ liệu tồn kho");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        add(jButton_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 630, 270, 70));

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_database_100px.png"))); // NOI18N
        jButton_Xoa.setText("Xóa dữ liệu tồn kho");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 630, 300, 70));

        jButton_BaoCaoXuatNhapKho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_BaoCaoXuatNhapKho.setText("Báo cáo xuất nhập kho");
        jButton_BaoCaoXuatNhapKho.setEnabled(false);
        jButton_BaoCaoXuatNhapKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BaoCaoXuatNhapKhoActionPerformed(evt);
            }
        });
        add(jButton_BaoCaoXuatNhapKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 430, 330, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Size");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 185, 89, -1));

        jTextField_Size.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_Size, new org.netbeans.lib.awtextra.AbsoluteConstraints(909, 182, 320, -1));

        jButton_ThemTonKho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ThemTonKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_add_100px.png"))); // NOI18N
        jButton_ThemTonKho.setText("Thêm dữ liệu tồn kho");
        jButton_ThemTonKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemTonKhoActionPerformed(evt);
            }
        });
        add(jButton_ThemTonKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 300, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void getKhoHangList (){
        DefaultTableModel model = (DefaultTableModel) jTable_Kho.getModel();      
        ArrayList<KhoHang_DTO> arrK = new ArrayList<>();
        ArrayList<SanPham_DTO> arrSP = new ArrayList<>();
        arrK = kBUS.getAllKhoHang();
        arrSP = spBUS.getAllSanPham();
        for(int i=0; i<arrK.size();i++){
            KhoHang_DTO kh = arrK.get(i);   
            for(int j=0; j<arrSP.size();j++){
                SanPham_DTO sp = arrSP.get(j);  
                if(kh.getMaSP().equals(sp.getMaSP())){
                    String maSP = kh.getMaSP();
                String tenSP = sp.getTenSP();
                String size = kh.getSize();
                int sl = kh.getSL();
                double giatien = sp.getGia();
                String tgCN = kh.getTGCapNhat();
                Object [] row = {i+1,maSP,tenSP,size,sl,giatien,tgCN};
                model.addRow(row);
                }               
            }        
        }      
    } 
    
    private void jButton_BaoCaoXuatNhapKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BaoCaoXuatNhapKhoActionPerformed
        jFrame_BaoCaoXuatNhapKho.setTitle("Báo cáo xuất nhập kho");
        jFrame_BaoCaoXuatNhapKho.setVisible(true);
    }//GEN-LAST:event_jButton_BaoCaoXuatNhapKhoActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable_Kho.getModel();
        model.setRowCount(0);
        getKhoHangList();
        jTextField_MaSanPham.setText("");
        jTextField_TenSanPham.setText("");
        jTextField_SoLuong.setText("");
        jTextField_GiaTien.setText("");
        jTextField_Size.setText("");
        jTextField_ThoiGianCapNhat.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        int i = jTable_Kho.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa dữ liệu tồn kho của sản phẩm: "+jTable_Kho.getValueAt(i, 2)+ ", size '"+jTable_Kho.getValueAt(i, 3) +"' khỏi hệ thống ?" );
        if(a==JOptionPane.YES_OPTION){
            KhoHang_DTO kh = new KhoHang_DTO();
            kh.setMaSP(jTable_Kho.getValueAt(i, 1)+"");
            kh.setSize(jTable_Kho.getValueAt(i, 3)+"");
            JOptionPane.showMessageDialog(this,kBUS.delKhoHang(kh));
            jButton_LamMoiActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jTable_KhoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_KhoMousePressed
        int i = jTable_Kho.getSelectedRow();
        jTextField_MaSanPham.setText(jTable_Kho.getValueAt(i, 1)+"");
        jTextField_TenSanPham.setText(jTable_Kho.getValueAt(i, 2)+"");
        jTextField_Size.setText(jTable_Kho.getValueAt(i, 3)+"");
        jTextField_SoLuong.setText(jTable_Kho.getValueAt(i, 4)+"");
        jTextField_GiaTien.setText(jTable_Kho.getValueAt(i, 5)+"");
        jTextField_ThoiGianCapNhat.setText(jTable_Kho.getValueAt(i, 6) +"");       
    }//GEN-LAST:event_jTable_KhoMousePressed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        try{            
                KhoHang_DTO kh =new KhoHang_DTO();
                int i = jTable_Kho.getSelectedRow();
                kh.setMaSP(jTextField_MaSanPham.getText());
                kh.setSize(jTextField_Size.getText());
                kh.setSL(Integer.parseInt(jTextField_SoLuong.getText()));
                kh.setTGCapNhat(jTextField_ThoiGianCapNhat.getText());
                int a = JOptionPane.showConfirmDialog(this, "Ban co chac muon sua thong tin ton kho ?");
                if(a==JOptionPane.YES_OPTION){
                    JOptionPane.showMessageDialog(this,kBUS.editKhoHang(kh));
                jButton_LamMoiActionPerformed(evt);
                }               
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_ThemTonKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemTonKhoActionPerformed
        jFrame_ThemDuLieuTonKho.setTitle("Thêm dữ liệu tồn kho");
        jFrame_ThemDuLieuTonKho.setVisible(true);
    }//GEN-LAST:event_jButton_ThemTonKhoActionPerformed

    private void jButton_ThemTonKho_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemTonKho_HuyActionPerformed
        int a = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa thoát" );
        if(a==JOptionPane.YES_OPTION){
            jFrame_ThemDuLieuTonKho.dispose();
        }
        jComboBox_ThemTonKho_TenSP.removeAllItems();
    }//GEN-LAST:event_jButton_ThemTonKho_HuyActionPerformed

    private void jButton_ThemTonKho_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemTonKho_LuuActionPerformed
        try{
            if(jComboBox_ThemTonKho_TenSP.getSelectedItem().equals("")||
                    jTextField_ThemTonKho_MaSP.getText().trim().equals("")||
                    jTextField_ThemTonKho_Size.getText().trim().equals("")||
                    jTextField_ThemTonKho_SL.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else{
                KhoHang_DTO kh = new KhoHang_DTO();
                kh.setMaSP(jTextField_ThemTonKho_MaSP.getText());
                kh.setSize(jTextField_ThemTonKho_Size.getText());               
                kh.setSL(Integer.parseInt(jTextField_ThemTonKho_SL.getText()));      
                SimpleDateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd");
//                date = JDayChooser.getDate();
                String ngaycapnhat = dateformat.format(date);
                kh.setTGCapNhat(ngaycapnhat);               
                JOptionPane.showMessageDialog(this,kBUS.addKhoHang(kh));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_ThemTonKho_LuuActionPerformed

    private void jTextField_ThemTonKho_TimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField_ThemTonKho_TimKiemCaretUpdate
        jComboBox_ThemTonKho_TenSP.removeAllItems();
        ArrayList<SanPham_DTO> arrSP = new ArrayList<>();
        arrSP = spBUS.findSanPham(jTextField_ThemTonKho_TimKiem.getText());
        for(int i=0; i<arrSP.size();i++){
            SanPham_DTO sp = arrSP.get(i);
            jComboBox_ThemTonKho_TenSP.addItem(sp.getTenSP());
        }        
    }//GEN-LAST:event_jTextField_ThemTonKho_TimKiemCaretUpdate

    private void jComboBox_ThemTonKho_TenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_ThemTonKho_TenSPActionPerformed
        ArrayList<SanPham_DTO> arr = new ArrayList<>();
        arr = spBUS.getAllSanPham();
        for(int i =0;i<arr.size();i++){
            SanPham_DTO sp = arr.get(i);
            if(sp.getTenSP().equals(jComboBox_ThemTonKho_TenSP.getSelectedItem())){
                jTextField_ThemTonKho_MaSP.setText(sp.getMaSP());
            }
        }
    }//GEN-LAST:event_jComboBox_ThemTonKho_TenSPActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jFrame_ThemDuLieuTonKhoWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame_ThemDuLieuTonKhoWindowClosing
        jFrame_ThemDuLieuTonKho.dispose();
    }//GEN-LAST:event_jFrame_ThemDuLieuTonKhoWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_BaoCaoXuatNhapKho;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_ThemTonKho;
    private javax.swing.JButton jButton_ThemTonKho_Huy;
    private javax.swing.JButton jButton_ThemTonKho_Luu;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JButton jButton_add;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox_ThemTonKho_TenSP;
    private javax.swing.JFrame jFrame_BaoCaoXuatNhapKho;
    private javax.swing.JFrame jFrame_ThemDuLieuTonKho;
    private javax.swing.JFrame jFrame_TimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_SL;
    private javax.swing.JLabel jLabel_capnhat;
    private javax.swing.JLabel jLabel_giatien;
    private javax.swing.JLabel jLabel_maSP;
    private javax.swing.JLabel jLabel_tenSP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable_Kho;
    private javax.swing.JTextField jTextField_GiaTien;
    private javax.swing.JTextField jTextField_MaSanPham;
    private javax.swing.JTextField jTextField_Size;
    private javax.swing.JTextField jTextField_SoLuong;
    private javax.swing.JTextField jTextField_TenSanPham;
    private javax.swing.JTextField jTextField_ThemTonKho_MaSP;
    private javax.swing.JTextField jTextField_ThemTonKho_SL;
    private javax.swing.JTextField jTextField_ThemTonKho_Size;
    private javax.swing.JTextField jTextField_ThemTonKho_TimKiem;
    private javax.swing.JTextField jTextField_ThoiGianCapNhat;
    // End of variables declaration//GEN-END:variables
}
