package GUI;
import BUS.CuaHang_BUS;
import DTO.CuaHang_DTO;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author trita
 */
public class Panel_Cua_Hang extends javax.swing.JPanel {
    CuaHang_BUS chBUS = new CuaHang_BUS();
    private ActionEvent evt;
    
    /**
     * Creates new form Panel_Cua_Hang
     */
    public Panel_Cua_Hang() {
        initComponents();
        getCuaHangList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton_Them = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jTextField_TenCuaHang = new javax.swing.JTextField();
        jTextField_DiaChi = new javax.swing.JTextField();
        jTextField_TinhTrang = new javax.swing.JTextField();
        jTextField_SoDienThoai = new javax.swing.JTextField();
        jButton_LamMoi = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField_MaCuaHang = new javax.swing.JTextField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("CỬA HÀNG");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 37));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách cửa hàng");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên cửa hàng", "Địa chỉ", "Tình trạng"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 592, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên cửa hàng");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Địa chỉ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, 85, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tình trạng");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 85, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số điện thoại");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 98, -1));

        jButton_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_add_100px.png"))); // NOI18N
        jButton_Them.setText("Thêm cửa hàng");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        add(jButton_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 610, 240, 60));

        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_edit_100px.png"))); // NOI18N
        jButton_Sua.setText("Sửa cửa hàng");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        add(jButton_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 610, 230, 60));

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_database_100px.png"))); // NOI18N
        jButton_Xoa.setText("Xóa cửa hàng");
        jButton_Xoa.setIconTextGap(10);
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 240, 60));

        jTextField_TenCuaHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_TenCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, 425, -1));

        jTextField_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 425, -1));

        jTextField_TinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_TinhTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, 425, -1));

        jTextField_SoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 425, -1));

        jButton_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_refresh_100px.png"))); // NOI18N
        jButton_LamMoi.setText("Làm mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 200, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mã cửa hàng");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        jTextField_MaCuaHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_MaCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 425, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void getCuaHangList(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<CuaHang_DTO> arr = new ArrayList<>();
        arr = chBUS.getAllCuaHang();
        for(int i =0;i<arr.size();i++){
            CuaHang_DTO ch = arr.get(i);
            String tench = ch.getTenCuaHang();
            String diachi= ch.getDiaChi();
            String tinhtrang = ch.getTinhTrang();
            Object[] row = {tench,diachi,tinhtrang};
            model.addRow(row);
        }
    }
    
    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        getCuaHangList();
        jTextField_MaCuaHang.setText("");
        jTextField_TenCuaHang.setText("");
        jTextField_DiaChi.setText("");
        jTextField_TinhTrang.setText("");
        jTextField_SoDienThoai.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        try{
            if(jTextField_MaCuaHang.getText().trim().equals("")||
                    jTextField_TenCuaHang.getText().trim().equals("")||
                    jTextField_DiaChi.getText().trim().equals("")||
                    jTextField_TinhTrang.getText().trim().equals("")||
                    jTextField_SoDienThoai.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else{
                CuaHang_DTO chDTO=new CuaHang_DTO();
                chDTO.setMaCH(jTextField_MaCuaHang.getText());
                chDTO.setTenCuaHang(jTextField_TenCuaHang.getText());
                chDTO.setDiaChi(jTextField_DiaChi.getText());
                chDTO.setTinhTrang(jTextField_TinhTrang.getText());
                chDTO.setSdt(jTextField_SoDienThoai.getText());
                JOptionPane.showMessageDialog(this,chBUS.addCuaHang(chDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
        
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        try{
            if(jTextField_MaCuaHang.getText().trim().equals("")){
                JOptionPane.showMessageDialog(this,"Vui lòng nhập mã cửa hàng");
            }
            else{
                CuaHang_DTO chDTO = new CuaHang_DTO();
                chDTO.setMaCH(jTextField_MaCuaHang.getText());
                JOptionPane.showMessageDialog(this,chBUS.delCuaHang(chDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        } catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
        
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        try{
            if(jTextField_MaCuaHang.getText().trim().equals("")||
                    jTextField_TenCuaHang.getText().trim().equals("")||
                    jTextField_DiaChi.getText().trim().equals("")||
                    jTextField_TinhTrang.getText().trim().equals("")||
                    jTextField_SoDienThoai.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng chọn cửa hàng cần sửa");
            else{
                CuaHang_DTO chDTO=new CuaHang_DTO();
                chDTO.setMaCH(jTextField_MaCuaHang.getText());
                chDTO.setTenCuaHang(jTextField_TenCuaHang.getText());
                chDTO.setDiaChi(jTextField_DiaChi.getText());
                chDTO.setTinhTrang(jTextField_TinhTrang.getText());
                chDTO.setSdt(jTextField_SoDienThoai.getText());
                JOptionPane.showMessageDialog(this,chBUS.editCuaHang(chDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        int i = jTable1.getSelectedRow();
        jTextField_TenCuaHang.setText(jTable1.getValueAt(i, 0)+"");
        jTextField_DiaChi.setText(jTable1.getValueAt(i, 1)+"");
        jTextField_TinhTrang.setText(jTable1.getValueAt(i, 2)+"");
        ArrayList<CuaHang_DTO> arr = new ArrayList<>();
        arr = chBUS.getAllCuaHang();
        for(int k=0;k<arr.size();k++){
            CuaHang_DTO ch = arr.get(k);
            if(ch.getTenCuaHang().equals(jTable1.getValueAt(i, 0)+"")){
                jTextField_MaCuaHang.setText(ch.getMaCH());
                jTextField_SoDienThoai.setText(ch.getSdt());
            }
        }
    }//GEN-LAST:event_jTable1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_DiaChi;
    private javax.swing.JTextField jTextField_MaCuaHang;
    private javax.swing.JTextField jTextField_SoDienThoai;
    private javax.swing.JTextField jTextField_TenCuaHang;
    private javax.swing.JTextField jTextField_TinhTrang;
    // End of variables declaration//GEN-END:variables
}
