package GUI;
import BUS.NhanVien_BUS;
import DTO.NhanVien_DTO;
import DTO.CuaHang_DTO;
import BUS.CuaHang_BUS;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author trita
 */
public class Panel_Nhan_Vien extends javax.swing.JPanel {
    
    NhanVien_BUS nvBUS = new NhanVien_BUS();
    CuaHang_BUS chBUS = new CuaHang_BUS();
   
    /**
     * Creates new form Nhan_Vien
     */
    public Panel_Nhan_Vien() {
        initComponents();
        getNhanVienList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_ChiTietNhanVien = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField_CTNV_MaNhanVien = new javax.swing.JTextField();
        jTextField_CTNV_DiaChi = new javax.swing.JTextField();
        jTextField_CTNV_HoTen = new javax.swing.JTextField();
        jTextField_CTNV_ChucVu = new javax.swing.JTextField();
        jTextField_CTNV_Luong = new javax.swing.JTextField();
        jTextField_CTNV_SDT = new javax.swing.JTextField();
        jTextField_CTNV_GioiTinh = new javax.swing.JTextField();
        jTextField_CTNV_NgaySinh = new javax.swing.JTextField();
        jTextField_CTNV_CMND_CCCD = new javax.swing.JTextField();
        jTextField_CTNV_QueQuan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_CTNV_HocVan = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_CTNV_CacKiNang = new javax.swing.JTextArea();
        jButton_CTNV_AnhChanDung = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_CTNV_KinhNghiemLamViec = new javax.swing.JTextArea();
        jButton_CTNV_Sua = new javax.swing.JButton();
        jButton_CTNV_Luu = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea_CTNV_DanhGiaKhachHang = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jTextField_CTNV_SLDanhGia = new javax.swing.JTextField();
        jComboBox_CTNV_ThuocCuaHang = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_MaNhanVien = new javax.swing.JTextField();
        jTextField_HoTenNhanVien = new javax.swing.JTextField();
        jTextField_ChucVu = new javax.swing.JTextField();
        jTextField_Sdt = new javax.swing.JTextField();
        jTextField_LuongCoBan = new javax.swing.JTextField();
        jTextField_SLDanhGia = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_DanhGia = new javax.swing.JTextArea();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_ChiTietNhanVien = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jComboBox_ThuocCuaHang = new javax.swing.JComboBox<>();

        jFrame_ChiTietNhanVien.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jFrame_ChiTietNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrame_ChiTietNhanVien.setMinimumSize(new java.awt.Dimension(1200, 750));
        jFrame_ChiTietNhanVien.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jFrame_ChiTietNhanVien.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame_ChiTietNhanVienWindowClosing(evt);
            }
        });

        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 750));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 750));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mã nhân viên");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Thuộc cửa hàng");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Họ tên");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Chức vụ");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Số điện thoại");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Lương cơ bản");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Giới tính");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Ngày sinh");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("CMND/CCCD");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Quê quán");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Địa chỉ");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Học vấn");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Các kĩ năng");

        jTextField_CTNV_MaNhanVien.setEditable(false);

        jTextArea_CTNV_HocVan.setColumns(20);
        jTextArea_CTNV_HocVan.setRows(5);
        jScrollPane2.setViewportView(jTextArea_CTNV_HocVan);

        jTextArea_CTNV_CacKiNang.setColumns(20);
        jTextArea_CTNV_CacKiNang.setRows(5);
        jScrollPane4.setViewportView(jTextArea_CTNV_CacKiNang);

        jButton_CTNV_AnhChanDung.setToolTipText("");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Kinh nghiệm làm việc");

        jTextArea_CTNV_KinhNghiemLamViec.setColumns(20);
        jTextArea_CTNV_KinhNghiemLamViec.setRows(5);
        jScrollPane5.setViewportView(jTextArea_CTNV_KinhNghiemLamViec);

        jButton_CTNV_Sua.setText("Sửa");
        jButton_CTNV_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CTNV_SuaActionPerformed(evt);
            }
        });

        jButton_CTNV_Luu.setText("Lưu");
        jButton_CTNV_Luu.setEnabled(false);
        jButton_CTNV_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CTNV_LuuActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("Đánh giá của khách hàng");

        jTextArea_CTNV_DanhGiaKhachHang.setColumns(20);
        jTextArea_CTNV_DanhGiaKhachHang.setRows(5);
        jScrollPane6.setViewportView(jTextArea_CTNV_DanhGiaKhachHang);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("Số lượt đánh giá");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(10, 10, 10)
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(354, 354, 354))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_CTNV_MaNhanVien, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_Luong, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_GioiTinh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_NgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_SDT, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_ChucVu, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_DiaChi, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_HoTen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_CTNV_CMND_CCCD)
                                    .addComponent(jTextField_CTNV_QueQuan)
                                    .addComponent(jComboBox_CTNV_ThuocCuaHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(173, 173, 173)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel25)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(jTextField_CTNV_SLDanhGia)
                                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))))))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton_CTNV_AnhChanDung, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(154, 154, 154))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton_CTNV_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(140, 140, 140)
                                                .addComponent(jButton_CTNV_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44))))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_CTNV_MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox_CTNV_ThuocCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_CTNV_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jTextField_CTNV_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_CTNV_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_CTNV_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField_CTNV_Luong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton_CTNV_AnhChanDung, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField_CTNV_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextField_CTNV_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextField_CTNV_CMND_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jTextField_CTNV_QueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_CTNV_SLDanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_CTNV_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_CTNV_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout jFrame_ChiTietNhanVienLayout = new javax.swing.GroupLayout(jFrame_ChiTietNhanVien.getContentPane());
        jFrame_ChiTietNhanVien.getContentPane().setLayout(jFrame_ChiTietNhanVienLayout);
        jFrame_ChiTietNhanVienLayout.setHorizontalGroup(
            jFrame_ChiTietNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_ChiTietNhanVienLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame_ChiTietNhanVienLayout.setVerticalGroup(
            jFrame_ChiTietNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setMinimumSize(new java.awt.Dimension(810, 580));
        setPreferredSize(new java.awt.Dimension(810, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Họ tên"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 101, 540, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách nhân viên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 57, 220, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 102, 109, 24));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Thuộc cửa hàng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 142, 109, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên nhân viên");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 180, 109, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Chức vụ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 218, 109, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 256, 109, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Lương cơ bản");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 294, 109, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Số lượt đánh giá");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 453, 109, -1));

        jTextField_MaNhanVien.setEditable(false);
        jTextField_MaNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_MaNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_MaNhanVienKeyPressed(evt);
            }
        });
        add(jTextField_MaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 101, 420, -1));

        jTextField_HoTenNhanVien.setEditable(false);
        jTextField_HoTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_HoTenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 177, 420, -1));

        jTextField_ChucVu.setEditable(false);
        jTextField_ChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_ChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 215, 420, -1));

        jTextField_Sdt.setEditable(false);
        jTextField_Sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_Sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 253, 420, -1));

        jTextField_LuongCoBan.setEditable(false);
        jTextField_LuongCoBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_LuongCoBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 291, 420, -1));

        jTextField_SLDanhGia.setEditable(false);
        jTextField_SLDanhGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SLDanhGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 453, 420, -1));

        jTextArea_DanhGia.setEditable(false);
        jTextArea_DanhGia.setColumns(20);
        jTextArea_DanhGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_DanhGia.setRows(5);
        jScrollPane3.setViewportView(jTextArea_DanhGia);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 335, 420, -1));

        jButton_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_refresh_100px.png"))); // NOI18N
        jButton_LamMoi.setText("Làm mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 220, 70));

        jButton_Them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_add_100px.png"))); // NOI18N
        jButton_Them.setText("Thêm nhân viên");
        jButton_Them.setEnabled(false);
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        add(jButton_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 620, -1, 70));

        jButton_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_database_100px.png"))); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.setEnabled(false);
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });
        add(jButton_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, 240, 70));

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_database_100px.png"))); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.setEnabled(false);
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 230, 70));

        jButton_ChiTietNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_ChiTietNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_more_details_100px.png"))); // NOI18N
        jButton_ChiTietNhanVien.setText("Chi tiết nhân viên");
        jButton_ChiTietNhanVien.setEnabled(false);
        jButton_ChiTietNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChiTietNhanVienActionPerformed(evt);
            }
        });
        add(jButton_ChiTietNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, 320, 70));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Đánh giá của khách");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 335, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("hàng");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 358, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 153, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 0, 102));
        jButton8.setText("NHÂN VIÊN");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, -1));

        jComboBox_ThuocCuaHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_ThuocCuaHang.setEnabled(false);
        add(jComboBox_ThuocCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 139, 420, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void getNhanVienList(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<NhanVien_DTO> arr = new ArrayList<>();
        arr = nvBUS.getAllNhanVien();
        for(int i =0;i<arr.size();i++){
            NhanVien_DTO nv = arr.get(i);
            String manv = nv.getMaNV();
            String hoten = nv.getHoTen();
            Object[] row = {i+1,manv,hoten};
            model.addRow(row);
        }
        ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
        arrCH=chBUS.getAllCuaHang();
        jComboBox_ThuocCuaHang.removeAllItems();
        for(int k =0;k<arrCH.size();k++){
            CuaHang_DTO ch = arrCH.get(k);
                jComboBox_ThuocCuaHang.addItem(ch.getTenCuaHang());
        }
        jComboBox_ThuocCuaHang.addItem(null);
        jComboBox_CTNV_ThuocCuaHang.removeAllItems();
        for(int j=0;j<jComboBox_ThuocCuaHang.getItemCount()-1;j++){
            jComboBox_CTNV_ThuocCuaHang.addItem(jComboBox_ThuocCuaHang.getItemAt(j));
        }
    }
    
    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        getNhanVienList();     
        jTextField_MaNhanVien.setText("");
        jTextField_MaNhanVien.setEditable(true);
        jComboBox_ThuocCuaHang.setEnabled(true);
        jComboBox_ThuocCuaHang.setSelectedItem(null);
        jTextField_HoTenNhanVien.setText("");
        jTextField_HoTenNhanVien.setEditable(true);
        jTextField_ChucVu.setText("");
        jTextField_ChucVu.setEditable(true);
        jTextField_Sdt.setText("");
        jTextField_Sdt.setEditable(true);
        jTextField_LuongCoBan.setText("");
        jTextField_LuongCoBan.setEditable(true);
        jTextArea_DanhGia.setText("");
        jTextArea_DanhGia.setEditable(true);
        jTextField_SLDanhGia.setText("");
        jTextField_SLDanhGia.setEditable(true); 
        jButton_ChiTietNhanVien.setEnabled(false);
        jButton_Xoa.setEnabled(false);
        jButton_TimKiem.setEnabled(false);
        jButton_Them.setEnabled(true);
        jButton_CTNV_Luu.setEnabled(false);
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_ChiTietNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChiTietNhanVienActionPerformed
        jFrame_ChiTietNhanVien.setTitle("Chi tiết nhân viên");
        jFrame_ChiTietNhanVien.setVisible(true);
        jButton_CTNV_Sua.setEnabled(true);
        jTextArea_CTNV_CacKiNang.setEditable(false);
            jTextArea_CTNV_HocVan.setEditable(false);
            jTextArea_CTNV_KinhNghiemLamViec.setEditable(false);
            jTextField_CTNV_CMND_CCCD.setEditable(false);
            jTextField_CTNV_ChucVu.setEditable(false);
            jTextField_CTNV_DiaChi.setEditable(false);
            jTextField_CTNV_GioiTinh.setEditable(false);
            jTextField_CTNV_HoTen.setEditable(false);
            jTextField_CTNV_Luong.setEditable(false);
            jTextField_CTNV_MaNhanVien.setEditable(false);
            jTextField_CTNV_NgaySinh.setEditable(false);
            jTextField_CTNV_QueQuan.setEditable(false);
            jTextField_CTNV_SDT.setEditable(false);
            jComboBox_CTNV_ThuocCuaHang.setEnabled(false);
            jTextArea_CTNV_DanhGiaKhachHang.setEditable(false);
            jTextField_CTNV_SLDanhGia.setEditable(false);
        int i = jTable1.getSelectedRow();
        jTextField_CTNV_MaNhanVien.setText(jTable1.getValueAt(i, 1)+"");
        jTextField_CTNV_HoTen.setText(jTable1.getValueAt(i, 2)+"");
        ArrayList<NhanVien_DTO> arr = new ArrayList<>();
        arr=nvBUS.getAllNhanVien();
        for(int k =0;k<arr.size();k++){
            NhanVien_DTO nv = arr.get(k);
            if(nv.getMaNV().equals(jTable1.getValueAt(i,1)+"")){
                jTextField_CTNV_DiaChi.setText(nv.getDiaChi()+"");
                jTextField_CTNV_ChucVu.setText(nv.getChucVu());
                jTextField_CTNV_SDT.setText(nv.getSdt());
                jTextField_CTNV_Luong.setText(nv.getLuongCoBan()+"");
                jTextField_CTNV_GioiTinh.setText(nv.getGioiTinh()+"");
                jTextField_CTNV_NgaySinh.setText(nv.getNgaySinh()+"");
                jTextField_CTNV_CMND_CCCD.setText(nv.getCMCN_CCCD()+"");
                jTextField_CTNV_QueQuan.setText(nv.getQueQuan()+"");
                jTextArea_CTNV_HocVan.setText(nv.getHocVan()+"");
                jTextArea_CTNV_CacKiNang.setText(nv.getKyNang()+"");
                jTextArea_CTNV_KinhNghiemLamViec.setText(nv.getKinhNghiem()+"");
                jTextArea_CTNV_DanhGiaKhachHang.setText(nv.getDanhGiaCuaKhachHang()+"");
                jTextField_CTNV_SLDanhGia.setText(nv.getSoLuongDanhGia()+"");
            }
        }
        for(int j =0 ; j<jComboBox_CTNV_ThuocCuaHang.getItemCount();j++){
            if(jComboBox_CTNV_ThuocCuaHang.getItemAt(j).equals(jComboBox_ThuocCuaHang.getSelectedItem())){
                jComboBox_CTNV_ThuocCuaHang.setSelectedIndex(j);
            }
        }        
    }//GEN-LAST:event_jButton_ChiTietNhanVienActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        jButton_ChiTietNhanVien.setEnabled(true);
        jButton_Xoa.setEnabled(true);
        jButton_Them.setEnabled(true);
        int i = jTable1.getSelectedRow();
        jTextField_MaNhanVien.setText(jTable1.getValueAt(i, 1)+"");
        jTextField_HoTenNhanVien.setText(jTable1.getValueAt(i, 2)+"");              
        ArrayList<NhanVien_DTO> arr = new ArrayList<>();
        ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
        arr=nvBUS.getAllNhanVien();
        arrCH=chBUS.getAllCuaHang();
        for(int k =0;k<arr.size();k++){
            NhanVien_DTO nv = arr.get(k);
            if(nv.getMaNV().equals(jTable1.getValueAt(i,1)+"")){                
                jTextField_ChucVu.setText(nv.getChucVu());
                jTextField_Sdt.setText(nv.getSdt());
                jTextField_LuongCoBan.setText(nv.getLuongCoBan()+"");
                jTextArea_DanhGia.setText(nv.getDanhGiaCuaKhachHang());
                jTextField_SLDanhGia.setText(nv.getSoLuongDanhGia()+"");
                for(int h=0;h<arrCH.size();h++){
                    CuaHang_DTO ch = arrCH.get(h);
                    if(ch.getMaCH().equals(nv.getMaCH())){
                    for(int j=0;j<jComboBox_ThuocCuaHang.getItemCount()-1;j++){
                        if(ch.getTenCuaHang().equals(jComboBox_ThuocCuaHang.getItemAt(j))){
                            jComboBox_ThuocCuaHang.setSelectedIndex(j);
                        }
                    }  
                    }
                }
            }
        }
        jTextField_MaNhanVien.setEditable(false);       
        jComboBox_ThuocCuaHang.setEnabled(false);
        jTextField_HoTenNhanVien.setEditable(false);
        jTextField_ChucVu.setEditable(false);
        jTextField_Sdt.setEditable(false);
        jTextField_LuongCoBan.setEditable(false);
        jTextArea_DanhGia.setEditable(false);
        jTextField_SLDanhGia.setEditable(false);
    }//GEN-LAST:event_jTable1MousePressed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        String str=jTextField_HoTenNhanVien.getText()+"";
        int a = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa nhân viên '"+str+"' khỏi hệ thống ?" );
        if(a==JOptionPane.YES_OPTION){
                NhanVien_DTO nvDTO = new NhanVien_DTO();
                nvDTO.setMaNV(jTextField_MaNhanVien.getText());
                JOptionPane.showMessageDialog(this,nvBUS.delNhanVIen(nvDTO));
                jButton_LamMoiActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_CTNV_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CTNV_SuaActionPerformed
        int a = JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn chỉnh sửa thông tin nhân viên ?");
        if(a==JOptionPane.YES_OPTION){            
            jTextArea_CTNV_CacKiNang.setEditable(true);
            jTextArea_CTNV_HocVan.setEditable(true);
            jTextArea_CTNV_KinhNghiemLamViec.setEditable(true);
            jTextField_CTNV_CMND_CCCD.setEditable(true);
            jTextField_CTNV_ChucVu.setEditable(true);
            jTextField_CTNV_DiaChi.setEditable(true);
            jTextField_CTNV_GioiTinh.setEditable(true);
            jTextField_CTNV_HoTen.setEditable(true);
            jTextField_CTNV_Luong.setEditable(true);
            jTextField_CTNV_NgaySinh.setEditable(true);
            jTextField_CTNV_QueQuan.setEditable(true);
            jTextField_CTNV_SDT.setEditable(true);
            jComboBox_CTNV_ThuocCuaHang.setEnabled(true);
            jTextArea_CTNV_DanhGiaKhachHang.setEditable(true);
            jTextField_CTNV_SLDanhGia.setEditable(true);
            jButton_CTNV_Sua.setEnabled(false);           
            jButton_CTNV_Luu.setEnabled(true);
        }
    }//GEN-LAST:event_jButton_CTNV_SuaActionPerformed

    private void jTextField_MaNhanVienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_MaNhanVienKeyPressed
        jButton_TimKiem.setEnabled(true);
    }//GEN-LAST:event_jTextField_MaNhanVienKeyPressed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        ArrayList<NhanVien_DTO> arr = new ArrayList<>();
        arr = nvBUS.getAllNhanVien();
        for(int i =0;i<arr.size();i++){ 
            NhanVien_DTO nv = arr.get(i);
            if(nv.getMaNV().equalsIgnoreCase(jTextField_MaNhanVien.getText())){
                String manv = nv.getMaNV();
                String hoten = nv.getHoTen();
                Object[] row = {1,manv,hoten};
                model.addRow(row);          
            }           
        }
        if(jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên !");
            
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        try{
            if(jTextField_MaNhanVien.getText().trim().equals("")||
                    jTextField_HoTenNhanVien.getText().trim().equals("")||
                    jTextField_ChucVu.getText().trim().equals("")||
                    jTextField_Sdt.getText().trim().equals("")||
                    jTextField_LuongCoBan.getText().trim().equals("")||
                    jTextArea_DanhGia.getText().trim().equals("")||
                    jTextField_SLDanhGia.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else{
                NhanVien_DTO nvDTO=new NhanVien_DTO();
                nvDTO.setMaNV(jTextField_MaNhanVien.getText());
                ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
                arrCH=chBUS.getAllCuaHang();
                for(int h=0;h<arrCH.size();h++){
                    CuaHang_DTO ch = arrCH.get(h);
                    if(ch.getTenCuaHang().equals(jComboBox_ThuocCuaHang.getSelectedItem())){
                        nvDTO.setMaCH(ch.getMaCH());
                    }
                }
                nvDTO.setHoTen(jTextField_HoTenNhanVien.getText());
                nvDTO.setChucVu(jTextField_ChucVu.getText());
                nvDTO.setSdt(jTextField_Sdt.getText());
                nvDTO.setLuongCoBan(Double.parseDouble(jTextField_LuongCoBan.getText()));
                nvDTO.setDanhGiaCuaKhachHang(jTextArea_DanhGia.getText());
                nvDTO.setSoLuongDanhGia(Integer.parseInt(jTextField_SLDanhGia.getText()));
                JOptionPane.showMessageDialog(this,nvBUS.addCuaHang(nvDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_CTNV_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CTNV_LuuActionPerformed
        try{
                NhanVien_DTO nvDTO=new NhanVien_DTO();
                nvDTO.setMaNV(jTextField_CTNV_MaNhanVien.getText());
                ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
                arrCH=chBUS.getAllCuaHang();
                for(int h=0;h<arrCH.size();h++){
                    CuaHang_DTO ch = arrCH.get(h);
                    if(ch.getTenCuaHang().equals(jComboBox_ThuocCuaHang.getSelectedItem())){
                        nvDTO.setMaCH(ch.getMaCH());
                    }
                }
                nvDTO.setHoTen(jTextField_CTNV_HoTen.getText());
                nvDTO.setDiaChi(jTextField_CTNV_DiaChi.getText());
                nvDTO.setChucVu(jTextField_CTNV_ChucVu.getText());
                nvDTO.setSdt(jTextField_CTNV_SDT.getText());
                nvDTO.setLuongCoBan(Double.parseDouble(jTextField_CTNV_Luong.getText()));
                nvDTO.setGioiTinh(jTextField_CTNV_GioiTinh.getText());
                nvDTO.setNgaySinh(jTextField_CTNV_NgaySinh.getText());
                nvDTO.setCMCN_CCCD(jTextField_CTNV_CMND_CCCD.getText());
                nvDTO.setQueQuan(jTextField_CTNV_QueQuan.getText());
                nvDTO.setHocVan(jTextArea_CTNV_HocVan.getText());
                nvDTO.setKyNang(jTextArea_CTNV_CacKiNang.getText());
                nvDTO.setKinhNghiem(jTextArea_CTNV_KinhNghiemLamViec.getText());
                nvDTO.setDanhGiaCuaKhachHang(jTextArea_CTNV_DanhGiaKhachHang.getText());
                nvDTO.setSoLuongDanhGia(Integer.parseInt(jTextField_CTNV_SLDanhGia.getText()));
                JOptionPane.showMessageDialog(this,nvBUS.editNhanVien(nvDTO));
                jButton_LamMoiActionPerformed(evt);                
                jFrame_ChiTietNhanVien.dispose();
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
        
    }//GEN-LAST:event_jButton_CTNV_LuuActionPerformed

    private void jFrame_ChiTietNhanVienWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame_ChiTietNhanVienWindowClosing
        jFrame_ChiTietNhanVien.dispose();
    }//GEN-LAST:event_jFrame_ChiTietNhanVienWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton_CTNV_AnhChanDung;
    private javax.swing.JButton jButton_CTNV_Luu;
    private javax.swing.JButton jButton_CTNV_Sua;
    private javax.swing.JButton jButton_ChiTietNhanVien;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_CTNV_ThuocCuaHang;
    private javax.swing.JComboBox<String> jComboBox_ThuocCuaHang;
    private javax.swing.JFrame jFrame_ChiTietNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea_CTNV_CacKiNang;
    private javax.swing.JTextArea jTextArea_CTNV_DanhGiaKhachHang;
    private javax.swing.JTextArea jTextArea_CTNV_HocVan;
    private javax.swing.JTextArea jTextArea_CTNV_KinhNghiemLamViec;
    private javax.swing.JTextArea jTextArea_DanhGia;
    private javax.swing.JTextField jTextField_CTNV_CMND_CCCD;
    private javax.swing.JTextField jTextField_CTNV_ChucVu;
    private javax.swing.JTextField jTextField_CTNV_DiaChi;
    private javax.swing.JTextField jTextField_CTNV_GioiTinh;
    private javax.swing.JTextField jTextField_CTNV_HoTen;
    private javax.swing.JTextField jTextField_CTNV_Luong;
    private javax.swing.JTextField jTextField_CTNV_MaNhanVien;
    private javax.swing.JTextField jTextField_CTNV_NgaySinh;
    private javax.swing.JTextField jTextField_CTNV_QueQuan;
    private javax.swing.JTextField jTextField_CTNV_SDT;
    private javax.swing.JTextField jTextField_CTNV_SLDanhGia;
    private javax.swing.JTextField jTextField_ChucVu;
    private javax.swing.JTextField jTextField_HoTenNhanVien;
    private javax.swing.JTextField jTextField_LuongCoBan;
    private javax.swing.JTextField jTextField_MaNhanVien;
    private javax.swing.JTextField jTextField_SLDanhGia;
    private javax.swing.JTextField jTextField_Sdt;
    // End of variables declaration//GEN-END:variables
}
