package GUI;
import BUS.*;
import DTO.*;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author trita
 */
public class Panel_Nha_Cung_Cap extends javax.swing.JPanel {
    NhaCungCap_BUS ncBUS = new NhaCungCap_BUS();
    SanPham_BUS spBUS = new SanPham_BUS();
    CuaHang_BUS chBUS = new CuaHang_BUS();
    NhanVien_BUS nvBUS = new NhanVien_BUS();
    PhieuDatHang_BUS pdhBUS = new PhieuDatHang_BUS();
    Date date = new Date();
    
    /**
     * Creates new form Panel_Nha_Cung_Cap
     */
    public Panel_Nha_Cung_Cap() {
        initComponents();
        jTable_DanhSachNhaCungCap.getColumnModel().getColumn(0).setPreferredWidth(4);   //chinh sua do rong cua cot
        getPhieuDatHangList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_ThemDonDatHang = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jTextField_ThemDonDat_MaPD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_TDD_DSSanPhamCanDat = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_TDD_SoLuong = new javax.swing.JTextField();
        jButton_TDD_Them = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable_TDD_DSSanPham = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_TDD_GhiChu = new javax.swing.JTextArea();
        jButton_TDD_Luu = new javax.swing.JButton();
        jButton_TDD_Huy = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField_TDD_TongTien = new javax.swing.JTextField();
        jDateChooser_TDD_NgayDat = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_TDD_MaNV = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jComboBox_TDD_CuaHang = new javax.swing.JComboBox<>();
        jButton_TDD_Xoa = new javax.swing.JButton();
        jFrame_LichSuDatHang = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_LichSuPhieuDat = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField_CTPD_MaPD = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable_ChiTietPhieuDat = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField_CTPD_TongTien = new javax.swing.JTextField();
        jFrame_ThongTinCacSPCC = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable_DSCacSPCC = new javax.swing.JTable();
        jLabel_TTSPCC_TenNC = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachNhaCungCap = new javax.swing.JTable();
        jButton_ThemDonDatHang = new javax.swing.JButton();
        jButton_LichSuDatHang = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_MaNC = new javax.swing.JTextField();
        jTextField_TenNC = new javax.swing.JTextField();
        jTextField_SDT = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea_DiaChi = new javax.swing.JTextArea();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_ThongTinCacSanPhamCungCap = new javax.swing.JButton();

        jFrame_ThemDonDatHang.setMinimumSize(new java.awt.Dimension(1024, 660));
        jFrame_ThemDonDatHang.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã đặt hàng");

        jTextField_ThemDonDat_MaPD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh sách sản phẩm cần đặt");

        jTable_TDD_DSSanPhamCanDat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_TDD_DSSanPhamCanDat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_TDD_DSSanPhamCanDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(jTable_TDD_DSSanPhamCanDat);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(448, 297));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng");

        jTextField_TDD_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField_TDD_SoLuong.setEnabled(false);

        jButton_TDD_Them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_TDD_Them.setText("Thêm");
        jButton_TDD_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TDD_ThemActionPerformed(evt);
            }
        });

        jTable_TDD_DSSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_TDD_DSSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP"
            }
        ));
        jTable_TDD_DSSanPham.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_TDD_DSSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_TDD_DSSanPhamMousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(jTable_TDD_DSSanPham);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Danh sách các sản phẩm ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_TDD_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton_TDD_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TDD_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton_TDD_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ghi chú");

        jTextArea_TDD_GhiChu.setColumns(20);
        jTextArea_TDD_GhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_TDD_GhiChu.setRows(5);
        jScrollPane3.setViewportView(jTextArea_TDD_GhiChu);

        jButton_TDD_Luu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_TDD_Luu.setText("Lưu");

        jButton_TDD_Huy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_TDD_Huy.setText("Hủy");
        jButton_TDD_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TDD_HuyActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tổng tiền");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jTextField_TDD_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ngày đặt");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Mã NV");

        jComboBox_TDD_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Cửa hàng");

        jComboBox_TDD_CuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TDD_CuaHangActionPerformed(evt);
            }
        });

        jButton_TDD_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_TDD_Xoa.setText("Xóa");
        jButton_TDD_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TDD_XoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame_ThemDonDatHangLayout = new javax.swing.GroupLayout(jFrame_ThemDonDatHang.getContentPane());
        jFrame_ThemDonDatHang.getContentPane().setLayout(jFrame_ThemDonDatHangLayout);
        jFrame_ThemDonDatHangLayout.setHorizontalGroup(
            jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 719, Short.MAX_VALUE))
                    .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                        .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                                .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame_ThemDonDatHangLayout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame_ThemDonDatHangLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_TDD_TongTien))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jButton_TDD_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(jButton_TDD_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_TDD_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47))
                                    .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_ThemDonDat_MaPD, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser_TDD_NgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_TDD_CuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_TDD_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jFrame_ThemDonDatHangLayout.setVerticalGroup(
            jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField_ThemDonDat_MaPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jComboBox_TDD_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jComboBox_TDD_CuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jDateChooser_TDD_NgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(8, 8, 8)
                .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField_TDD_TongTien))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jFrame_ThemDonDatHangLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(jFrame_ThemDonDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_TDD_Huy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_TDD_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_TDD_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(37, 37, 37))
        );

        jFrame_LichSuDatHang.setMinimumSize(new java.awt.Dimension(1350, 540));
        jFrame_LichSuDatHang.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jTable_LichSuPhieuDat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_LichSuPhieuDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã đơn đặt hàng", "Số lượng mặt hàng", "Số tiền phải trả", "Nhà cung cấp", "Ngày đặt hàng"
            }
        ));
        jTable_LichSuPhieuDat.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_LichSuPhieuDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_LichSuPhieuDatMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTable_LichSuPhieuDat);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Chi tiết đơn đặt hàng");

        jTextField_CTPD_MaPD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable_ChiTietPhieuDat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_ChiTietPhieuDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Số tiền/1sp", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane5.setViewportView(jTable_ChiTietPhieuDat);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tổng tiền");

        jTextField_CTPD_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jFrame_LichSuDatHangLayout = new javax.swing.GroupLayout(jFrame_LichSuDatHang.getContentPane());
        jFrame_LichSuDatHang.getContentPane().setLayout(jFrame_LichSuDatHangLayout);
        jFrame_LichSuDatHangLayout.setHorizontalGroup(
            jFrame_LichSuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_LichSuDatHangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame_LichSuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrame_LichSuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jFrame_LichSuDatHangLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField_CTPD_MaPD, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame_LichSuDatHangLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_CTPD_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jFrame_LichSuDatHangLayout.setVerticalGroup(
            jFrame_LichSuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_LichSuDatHangLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jFrame_LichSuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jFrame_LichSuDatHangLayout.createSequentialGroup()
                        .addGroup(jFrame_LichSuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_CTPD_MaPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_LichSuDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_CTPD_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jFrame_ThongTinCacSPCC.setTitle("Thông tin các sản phẩm cung cấp");
        jFrame_ThongTinCacSPCC.setMinimumSize(new java.awt.Dimension(700, 400));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("Danh sách các sản phẩm đươc cung cấp bởi nhà cung cấp");

        jTable_DSCacSPCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên SP"
            }
        ));
        jScrollPane8.setViewportView(jTable_DSCacSPCC);

        jLabel_TTSPCC_TenNC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jFrame_ThongTinCacSPCCLayout = new javax.swing.GroupLayout(jFrame_ThongTinCacSPCC.getContentPane());
        jFrame_ThongTinCacSPCC.getContentPane().setLayout(jFrame_ThongTinCacSPCCLayout);
        jFrame_ThongTinCacSPCCLayout.setHorizontalGroup(
            jFrame_ThongTinCacSPCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_ThongTinCacSPCCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jFrame_ThongTinCacSPCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_ThongTinCacSPCCLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame_ThongTinCacSPCCLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_TTSPCC_TenNC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jFrame_ThongTinCacSPCCLayout.setVerticalGroup(
            jFrame_ThongTinCacSPCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_ThongTinCacSPCCLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jFrame_ThongTinCacSPCCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_TTSPCC_TenNC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("NHÀ CUNG CẤP");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 36));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách nhà cung cấp");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jTable_DanhSachNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_DanhSachNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã NCC", "Tên NCC", "Số điện thoại", "Địa chỉ"
            }
        ));
        jTable_DanhSachNhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable_DanhSachNhaCungCap.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_DanhSachNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_DanhSachNhaCungCapMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachNhaCungCap);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 613, 520));

        jButton_ThemDonDatHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ThemDonDatHang.setText("Thêm đơn đặt hàng");
        jButton_ThemDonDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemDonDatHangActionPerformed(evt);
            }
        });
        add(jButton_ThemDonDatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 430, 40));

        jButton_LichSuDatHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LichSuDatHang.setText("Lịch sử đặt hàng");
        jButton_LichSuDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LichSuDatHangActionPerformed(evt);
            }
        });
        add(jButton_LichSuDatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 430, 40));

        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_edit_100px.png"))); // NOI18N
        jButton_Sua.setText("Sửa nhà cung");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        add(jButton_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 680, 240, 60));

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_database_100px.png"))); // NOI18N
        jButton_Xoa.setText("Xóa nhà cung");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 680, 240, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mã nhà cung cấp");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 99, 111, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tên nhà cung cấp");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 151, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Số điện thoại");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 206, 111, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Địa chỉ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 264, 108, -1));

        jTextField_MaNC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_MaNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 96, 400, -1));

        jTextField_TenNC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_TenNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 148, 400, -1));

        jTextField_SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 206, 400, -1));

        jTextArea_DiaChi.setColumns(20);
        jTextArea_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea_DiaChi.setRows(5);
        jScrollPane6.setViewportView(jTextArea_DiaChi);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(811, 264, 400, -1));

        jButton_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_refresh_100px.png"))); // NOI18N
        jButton_LamMoi.setText("Làm mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 210, 60));

        jButton_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_add_100px.png"))); // NOI18N
        jButton_Them.setText("Thêm nhà cung");
        jButton_Them.setToolTipText("");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        add(jButton_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, 250, 60));

        jButton_ThongTinCacSanPhamCungCap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ThongTinCacSanPhamCungCap.setText("Thông tin các sản phẩm cung cấp");
        jButton_ThongTinCacSanPhamCungCap.setEnabled(false);
        jButton_ThongTinCacSanPhamCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThongTinCacSanPhamCungCapActionPerformed(evt);
            }
        });
        add(jButton_ThongTinCacSanPhamCungCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 426, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void getPhieuDatHangList(){
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachNhaCungCap.getModel();
        ArrayList<NhaCungCap_DTO> arrNC = new ArrayList<>();
        arrNC = ncBUS.getAllNhaCung();
        for(int k =0;k<arrNC.size();k++){
            NhaCungCap_DTO nc = arrNC.get(k);
            String maNC = nc.getMaNC();
            String tenNC = nc.getTenNC();
            String sdt = nc.getSdt();
            String diachi = nc.getDiachi();
            Object[] row = {k+1,maNC,tenNC,sdt,diachi};
            model.addRow(row);
        }
    }
    
    private void jButton_LichSuDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LichSuDatHangActionPerformed
        jFrame_LichSuDatHang.setTitle("Lịch sử đơn đặt hàng");
        jFrame_LichSuDatHang.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable_LichSuPhieuDat.getModel();
        ArrayList<LichSuPhieuDat_DTO> arrLSPD = new ArrayList<>();
        arrLSPD = pdhBUS.getAllLichSuPhieuDat();
        for(int k =0;k<arrLSPD.size();k++){
            LichSuPhieuDat_DTO lspd = arrLSPD.get(k);
            String mapd = lspd.getMaPD();
            String soluong = lspd.getTongsoluong();
            Double sotien = lspd.getTongtien();
            String nhacc = lspd.getMaNC();
            String ngaydat = lspd.getNgayDat();
            Object[] row = {k+1,mapd,soluong,sotien,nhacc,ngaydat};
            model.addRow(row);
        }
    }//GEN-LAST:event_jButton_LichSuDatHangActionPerformed

    private void jButton_ThemDonDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemDonDatHangActionPerformed
        jFrame_ThemDonDatHang.setTitle("Chi tiết đơn đặt");
        jFrame_ThemDonDatHang.setVisible(true);
        ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
        arrCH = chBUS.getAllCuaHang();       
        jComboBox_TDD_CuaHang.removeAllItems();
        for(int i =0 ;i<arrCH.size();i++){
            CuaHang_DTO ch = arrCH.get(i);
            jComboBox_TDD_CuaHang.addItem(ch.getMaCH());
        }       
        DefaultTableModel model = (DefaultTableModel) jTable_TDD_DSSanPham.getModel();
        int i =  jTable_DanhSachNhaCungCap.getSelectedRow();
        model.setRowCount(0);
        ArrayList<SanPham_DTO> arrSP = new ArrayList<>();
        arrSP = spBUS.getAllSanPham();
        int stt =0;
        for(int k =0;k<arrSP.size();k++){
            SanPham_DTO sp = arrSP.get(k);
            if(sp.getMaNC().equals(jTable_DanhSachNhaCungCap.getValueAt(i,1))){
                String maSP = sp.getMaSP();
                String tenSP = sp.getTenSP();
                stt++;
                Object[] row = {stt,maSP,tenSP};
                model.addRow(row);
            }        
        }
        DefaultTableModel model1 = (DefaultTableModel) jTable_TDD_DSSanPhamCanDat.getModel();
        model1.setRowCount(0);
    }//GEN-LAST:event_jButton_ThemDonDatHangActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachNhaCungCap.getModel();
        model.setRowCount(0);
        getPhieuDatHangList();
        jTextField_MaNC.setText("");
        jTextField_SDT.setText("");
        jTextField_TenNC.setText("");
        jTextArea_DiaChi.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jTable_DanhSachNhaCungCapMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachNhaCungCapMousePressed
        jButton_ThongTinCacSanPhamCungCap.setEnabled(true);
        int i = jTable_DanhSachNhaCungCap.getSelectedRow();
        ArrayList<NhaCungCap_DTO> arrNC = new ArrayList<>();
        arrNC= ncBUS.getAllNhaCung();
        for(int k =0;k<arrNC.size();k++){
            NhaCungCap_DTO nc = arrNC.get(k);
            if(nc.getMaNC().equals(jTable_DanhSachNhaCungCap.getValueAt(i,1)+"")){                           
                jTextField_MaNC.setText(nc.getMaNC()+"");
                jTextField_SDT.setText(nc.getSdt()+"");
                jTextField_TenNC.setText(nc.getTenNC()+"");
                jTextArea_DiaChi.setText(nc.getDiachi()+"");
            }
        }
    }//GEN-LAST:event_jTable_DanhSachNhaCungCapMousePressed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        try{
            if(jTextField_MaNC.getText().trim().equals("")||
                    jTextField_SDT.getText().trim().equals("")||
                    jTextField_TenNC.getText().trim().equals("")||
                     jTextArea_DiaChi.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else{
                NhaCungCap_DTO ncDTO = new NhaCungCap_DTO();
                ncDTO.setMaNC(jTextField_MaNC.getText());
                ncDTO.setTenNC(jTextField_TenNC.getText());               
                ncDTO.setSdt(jTextField_SDT.getText());      
                ncDTO.setDiachi(jTextArea_DiaChi.getText());
                JOptionPane.showMessageDialog(this,ncBUS.addNhaCungCap(ncDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        int i = jTable_DanhSachNhaCungCap.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa nhà cung cấp '"+jTable_DanhSachNhaCungCap.getValueAt(i, 2)+"' khỏi hệ thống ?" );
        if(a==JOptionPane.YES_OPTION){
            NhaCungCap_DTO ncDTO = new NhaCungCap_DTO();
            ncDTO.setMaNC(jTable_DanhSachNhaCungCap.getValueAt(i, 1)+"");
            JOptionPane.showMessageDialog(this,ncBUS.delNhaCungCap(ncDTO));
            jButton_LamMoiActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        try{
            if(jTextField_MaNC.getText().trim().equals("")||
                    jTextField_TenNC.getText().trim().equals("")||
                    jTextArea_DiaChi.getText().trim().equals("")||
                    jTextField_SDT.getText().trim().equals("")
                )
                JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung c?p cần sửa");
            else{
                NhaCungCap_DTO ncDTO = new NhaCungCap_DTO();
                ncDTO.setMaNC(jTextField_MaNC.getText());
                ncDTO.setTenNC(jTextField_TenNC.getText());
                ncDTO.setDiachi(jTextArea_DiaChi.getText());
                ncDTO.setSdt(jTextField_SDT.getText());
                JOptionPane.showMessageDialog(this,ncBUS.editNhaCungCap(ncDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_SuaActionPerformed

    private void jButton_ThongTinCacSanPhamCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThongTinCacSanPhamCungCapActionPerformed
       jFrame_ThongTinCacSPCC.setVisible(true);
       DefaultTableModel model = (DefaultTableModel) jTable_DSCacSPCC.getModel();
       int i =  jTable_DanhSachNhaCungCap.getSelectedRow();
       jLabel_TTSPCC_TenNC.setText(jTable_DanhSachNhaCungCap.getValueAt(i,1)+"");
       model.setRowCount(0);
       ArrayList<SanPham_DTO> arrSP = new ArrayList<>();
        arrSP = spBUS.getAllSanPham();
        int stt =0;
        for(int k =0;k<arrSP.size();k++){
            SanPham_DTO sp = arrSP.get(k);
            if(sp.getMaNC().equals(jTable_DanhSachNhaCungCap.getValueAt(i, 1))){
                String maSP = sp.getMaSP();
                String tenSP = sp.getTenSP();
                stt++;
                Object[] row = {stt,maSP,tenSP};
                model.addRow(row);
            }        
        }
    }//GEN-LAST:event_jButton_ThongTinCacSanPhamCungCapActionPerformed

    private void jComboBox_TDD_CuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TDD_CuaHangActionPerformed
        ArrayList<NhanVien_DTO> arrNV = new ArrayList<>();
        arrNV = nvBUS.getAllNhanVien();
        jComboBox_TDD_MaNV.removeAllItems();
        for(int i =0 ; i<arrNV.size();i++){
            NhanVien_DTO nv = arrNV.get(i);
            if(nv.getMaCH().equals(jComboBox_TDD_CuaHang.getSelectedItem())){
                jComboBox_TDD_MaNV.addItem(nv.getMaNV());
            }
        }       
    }//GEN-LAST:event_jComboBox_TDD_CuaHangActionPerformed

    private void jButton_TDD_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TDD_ThemActionPerformed
        if(jTextField_TDD_SoLuong.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        else{   
               DefaultTableModel model = (DefaultTableModel) jTable_TDD_DSSanPhamCanDat.getModel();
                int a = jTable_TDD_DSSanPham.getSelectedRow();    
                ArrayList<SanPham_DTO> arrSP = new ArrayList<>();
                arrSP = spBUS.getAllSanPham();
                for(int i=0;i<arrSP.size();i++){
                    SanPham_DTO sp = arrSP.get(i);
                    if(sp.getMaSP().equals(jTable_TDD_DSSanPham.getValueAt(a, 1))){
                        String maSP = sp.getMaSP();
                        String tenSP = sp.getTenSP();
                        String soluong = jTextField_TDD_SoLuong.getText();
                        String thanhtien = (sp.getGia()*Integer.parseInt(jTextField_TDD_SoLuong.getText()))+"";
                        Object[] row = {maSP,tenSP,soluong,thanhtien};
                        model.addRow(row);
                    }
                }  
         }        
        double tongtien =0;
        for(int i=0;i<jTable_TDD_DSSanPhamCanDat.getRowCount();i++){
            tongtien += Double.parseDouble(jTable_TDD_DSSanPhamCanDat.getValueAt(i, 3)+"");
        }
        jTextField_TDD_TongTien.setText(tongtien+"");
    }//GEN-LAST:event_jButton_TDD_ThemActionPerformed

    private void jTable_TDD_DSSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_TDD_DSSanPhamMousePressed
        jTextField_TDD_SoLuong.setEnabled(true);
        jTextField_TDD_SoLuong.setText("");
    }//GEN-LAST:event_jTable_TDD_DSSanPhamMousePressed

    private void jButton_TDD_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TDD_HuyActionPerformed
        int a = JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn thoát? Hãy chắc chắn rằng tất cả thông tin đã được lưu.");
        if(a==JOptionPane.YES_OPTION){
            jFrame_ThemDonDatHang.dispose();
        }
    }//GEN-LAST:event_jButton_TDD_HuyActionPerformed

    private void jButton_TDD_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TDD_XoaActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable_TDD_DSSanPhamCanDat.getModel();
        int a= jTable_TDD_DSSanPhamCanDat.getSelectedRow();
        model.removeRow(a);
        double tongtien =0;
        for(int i=0;i<jTable_TDD_DSSanPhamCanDat.getRowCount();i++){
            tongtien += Double.parseDouble(jTable_TDD_DSSanPhamCanDat.getValueAt(i, 3)+"");
        }
        jTextField_TDD_TongTien.setText(tongtien+"");
    }//GEN-LAST:event_jButton_TDD_XoaActionPerformed

    private void jTable_LichSuPhieuDatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_LichSuPhieuDatMousePressed
        int a = jTable_LichSuPhieuDat.getSelectedRow();
        jTextField_CTPD_MaPD.setText(jTable_LichSuPhieuDat.getValueAt(a, 1)+"");
        DefaultTableModel model = (DefaultTableModel) jTable_ChiTietPhieuDat.getModel();
        model.setRowCount(0);
        double tongtien = 0;
        ArrayList<ChiTietPhieuDat_DTO> arrCTPD = new ArrayList<>();
        arrCTPD = pdhBUS.getAllChiTietPhieuDat();
                for(int i=0;i<arrCTPD.size();i++){
                    ChiTietPhieuDat_DTO ctpd = arrCTPD.get(i);
                    if(ctpd.getMaPD().equals(jTable_LichSuPhieuDat.getValueAt(a, 1))){
                        String maSP = ctpd.getMaSP();
                        String tenSP = ctpd.getTenSP();
                        Double gia = ctpd.getGia();
                        int soluong = ctpd.getSl();
                        Double thanhtien = ctpd.getThanhTien();
                        tongtien += ctpd.getThanhTien();
                        Object[] row = {maSP,tenSP,gia,soluong,thanhtien};
                        model.addRow(row);
                    }
                }
        jTextField_CTPD_TongTien.setText(tongtien+"");
    }//GEN-LAST:event_jTable_LichSuPhieuDatMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_LichSuDatHang;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_TDD_Huy;
    private javax.swing.JButton jButton_TDD_Luu;
    private javax.swing.JButton jButton_TDD_Them;
    private javax.swing.JButton jButton_TDD_Xoa;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_ThemDonDatHang;
    private javax.swing.JButton jButton_ThongTinCacSanPhamCungCap;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_TDD_CuaHang;
    private javax.swing.JComboBox<String> jComboBox_TDD_MaNV;
    private com.toedter.calendar.JDateChooser jDateChooser_TDD_NgayDat;
    private javax.swing.JFrame jFrame_LichSuDatHang;
    private javax.swing.JFrame jFrame_ThemDonDatHang;
    private javax.swing.JFrame jFrame_ThongTinCacSPCC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_TTSPCC_TenNC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable_ChiTietPhieuDat;
    private javax.swing.JTable jTable_DSCacSPCC;
    private javax.swing.JTable jTable_DanhSachNhaCungCap;
    private javax.swing.JTable jTable_LichSuPhieuDat;
    private javax.swing.JTable jTable_TDD_DSSanPham;
    private javax.swing.JTable jTable_TDD_DSSanPhamCanDat;
    private javax.swing.JTextArea jTextArea_DiaChi;
    private javax.swing.JTextArea jTextArea_TDD_GhiChu;
    private javax.swing.JTextField jTextField_CTPD_MaPD;
    private javax.swing.JTextField jTextField_CTPD_TongTien;
    private javax.swing.JTextField jTextField_MaNC;
    private javax.swing.JTextField jTextField_SDT;
    private javax.swing.JTextField jTextField_TDD_SoLuong;
    private javax.swing.JTextField jTextField_TDD_TongTien;
    private javax.swing.JTextField jTextField_TenNC;
    private javax.swing.JTextField jTextField_ThemDonDat_MaPD;
    // End of variables declaration//GEN-END:variables
}
