/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;
import BUS.*;
import DTO.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.*;

/**
 *
 * @author trita
 */
public class Panel_Hoa_Don_Chi_Tra extends javax.swing.JPanel {
    HoaDonChiTra_BUS hdctBUS = new HoaDonChiTra_BUS();
    PhieuGiaoHang_BUS pghBUS = new PhieuGiaoHang_BUS();
    
    /**
     * Creates new form Panel_Hoa_Don_Tri_Tra
     */
    public Panel_Hoa_Don_Chi_Tra() {
        initComponents();
        getHoaDonChiTraList();
        getPhieuGiaoHangList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane_DanhSachHoaDonChiTra = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachHoaDonChiTra = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_DanhSachPhieuGiaoHang = new javax.swing.JTable();

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("HÓA ĐƠN CHI TRẢ");
        jButton1.setToolTipText("");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jTabbedPane_DanhSachHoaDonChiTra.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTabbedPane_DanhSachHoaDonChiTra.setDoubleBuffered(true);
        jTabbedPane_DanhSachHoaDonChiTra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTabbedPane_DanhSachHoaDonChiTra.setNextFocusableComponent(jTabbedPane_DanhSachHoaDonChiTra);

        jTable_DanhSachHoaDonChiTra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MA HOA DON", "NHAN VIEN LAP", "CUA HANG", "NGAY LAP", "MO TA", "TONG TIEN"
            }
        ));
        jTable_DanhSachHoaDonChiTra.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable_DanhSachHoaDonChiTra);

        jTabbedPane_DanhSachHoaDonChiTra.addTab("Danh sách hóa đơn chi trả", jScrollPane1);

        jTable_DanhSachPhieuGiaoHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MA PHIEU GIAO", "MA PHIEU DAT", "NHAN VIEN KIEM TRA", "CUA HANG", "NHA CUNG CAP", "NGAY DAT", "NGAY GIAO", "TONG TIEN"
            }
        ));
        jScrollPane2.setViewportView(jTable_DanhSachPhieuGiaoHang);

        jTabbedPane_DanhSachHoaDonChiTra.addTab("Danh sách phiếu giao hàng ", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 1175, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane_DanhSachHoaDonChiTra, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane_DanhSachHoaDonChiTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane_DanhSachHoaDonChiTra.getAccessibleContext().setAccessibleName("");
        jTabbedPane_DanhSachHoaDonChiTra.getAccessibleContext().setAccessibleParent(jTabbedPane_DanhSachHoaDonChiTra);
    }// </editor-fold>//GEN-END:initComponents

    private void getHoaDonChiTraList(){
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachHoaDonChiTra.getModel();
        ArrayList<HoaDonChiTra_DTO> arr = new ArrayList<>();
        arr = hdctBUS.getAllHoaDonChiTra();
        for(int i =0;i<arr.size();i++){
            HoaDonChiTra_DTO hdct = arr.get(i);
            String mahdct = hdct.getMaHDCT();
            String manv = hdct.getMaNV();
            String mach = hdct.getMaCH();
            String ngaylap= hdct.getNgayLap();
            String mota = hdct.getMoTa();
            double tongtien = hdct.getTongTien();
            Object[] row = {i+1,mahdct,manv,mach,ngaylap,mota,tongtien};
            model.addRow(row);
        }
    }
    
    private void getPhieuGiaoHangList(){
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachPhieuGiaoHang.getModel();
        ArrayList<PhieuGiaoHang_DTO> arrPGH = new ArrayList<>();
        arrPGH = pghBUS.getAllPhieuGiaoHang();
        for(int i =0;i<arrPGH.size();i++){
            PhieuGiaoHang_DTO pgh = arrPGH.get(i);
            String mapd = pgh.getMaPD();
            String mapg = pgh.getMaPG();
            String nv = pgh.getMaNV();
            String ch = pgh.getMaCH();
            String ncc = pgh.getMaNC();
            String ngaydat = pgh.getNgaydat();
            String ngaygiao = pgh.getNgaygiao();
            Double tongtien = pgh.getTongtien();
            Object[] row = {i+1,mapg,mapd,nv,ch,ncc,ngaydat,ngaygiao,tongtien};
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane_DanhSachHoaDonChiTra;
    private javax.swing.JTable jTable_DanhSachHoaDonChiTra;
    private javax.swing.JTable jTable_DanhSachPhieuGiaoHang;
    // End of variables declaration//GEN-END:variables
}
