package GUI;
import BUS.KhachHang_BUS;
import BUS.HoaDon_BUS;
import DTO.KhachHang_DTO;
import DTO.HoaDon_DTO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author trita
 */
public class Panel_Khach_Hang extends javax.swing.JPanel {
    KhachHang_BUS khBUS = new KhachHang_BUS();
    HoaDon_BUS hdBUS = new HoaDon_BUS();
    /**
     * Creates new form Panel_Khach_Hang
     */
    public Panel_Khach_Hang() {
        initComponents();
        getKhachHangList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_ChiTietKhachHang = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_CTKH_MaKH = new javax.swing.JTextField();
        jTextField_CTKH_TenKH = new javax.swing.JTextField();
        jTextField_CTKH_Sdt = new javax.swing.JTextField();
        jTextField_CTKH_XepHang = new javax.swing.JTextField();
        jTextField_CTKH_GioiTinh = new javax.swing.JTextField();
        jTextField_CTKH_CMND_CCCD = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_CTKH = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextField_CTKH_TongTienTichLuy = new javax.swing.JTextField();
        jButton_CTKH_Sua = new javax.swing.JButton();
        jButton_CTKH_Luu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_CTKH_DiaChi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachKhachHang = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_MaKhachHang = new javax.swing.JTextField();
        jTextField_TenKhachHang = new javax.swing.JTextField();
        jTextField_XepHangThanThiet = new javax.swing.JTextField();
        jTextField_SoTienMuaHangTichLuy = new javax.swing.JTextField();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_ChiTietKhachHang = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_DiaChi = new javax.swing.JTextArea();

        jFrame_ChiTietKhachHang.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrame_ChiTietKhachHang.setMinimumSize(new java.awt.Dimension(1000, 714));
        jFrame_ChiTietKhachHang.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        jFrame_ChiTietKhachHang.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jFrame_ChiTietKhachHangWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã khách hàng");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tên khách hàng");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Số điện thoại");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Xếp hạng");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Giới tính");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("CMND/CCCD");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Địa chỉ");

        jTextField_CTKH_MaKH.setEditable(false);
        jTextField_CTKH_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_CTKH_TenKH.setEditable(false);
        jTextField_CTKH_TenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_CTKH_Sdt.setEditable(false);
        jTextField_CTKH_Sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_CTKH_XepHang.setEditable(false);
        jTextField_CTKH_XepHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_CTKH_GioiTinh.setEditable(false);
        jTextField_CTKH_GioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTextField_CTKH_CMND_CCCD.setEditable(false);
        jTextField_CTKH_CMND_CCCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTable_CTKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Thời gian thanh toán", "Tổng tiền"
            }
        ));
        jScrollPane2.setViewportView(jTable_CTKH);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tổng tiền mua hàng tích lũy tháng này");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jTextField_CTKH_TongTienTichLuy.setEditable(false);
        jTextField_CTKH_TongTienTichLuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton_CTKH_Sua.setText("Sửa");
        jButton_CTKH_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CTKH_SuaActionPerformed(evt);
            }
        });

        jButton_CTKH_Luu.setText("Lưu");
        jButton_CTKH_Luu.setOpaque(true);
        jButton_CTKH_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CTKH_LuuActionPerformed(evt);
            }
        });

        jTextArea_CTKH_DiaChi.setEditable(false);
        jTextArea_CTKH_DiaChi.setColumns(20);
        jTextArea_CTKH_DiaChi.setRows(5);
        jScrollPane3.setViewportView(jTextArea_CTKH_DiaChi);

        javax.swing.GroupLayout jFrame_ChiTietKhachHangLayout = new javax.swing.GroupLayout(jFrame_ChiTietKhachHang.getContentPane());
        jFrame_ChiTietKhachHang.getContentPane().setLayout(jFrame_ChiTietKhachHangLayout);
        jFrame_ChiTietKhachHangLayout.setHorizontalGroup(
            jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_CTKH_TenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jTextField_CTKH_Sdt)
                            .addComponent(jTextField_CTKH_XepHang)
                            .addComponent(jTextField_CTKH_MaKH))
                        .addGap(49, 49, 49)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_CTKH_GioiTinh)
                            .addComponent(jTextField_CTKH_CMND_CCCD)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_CTKH_TongTienTichLuy, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                    .addGroup(jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_CTKH_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(jButton_CTKH_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)))
                .addContainerGap())
        );
        jFrame_ChiTietKhachHangLayout.setVerticalGroup(
            jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_CTKH_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_CTKH_TenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_CTKH_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_CTKH_XepHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_CTKH_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_CTKH_CMND_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jFrame_ChiTietKhachHangLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(44, 44, 44))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_CTKH_TongTienTichLuy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jFrame_ChiTietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_CTKH_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_CTKH_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Danh sách khách hàng thân thiết");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jTable_DanhSachKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã khách hàng", "Tên khách hàng"
            }
        ));
        jTable_DanhSachKhachHang.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_DanhSachKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_DanhSachKhachHangMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachKhachHang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 520, 480));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã khách hàng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 125, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên khách hàng");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 125, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Địa chỉ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 125, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Xếp hạng thân thiết");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số tiền mua hàng");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, 125, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("tích lũy");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 104, -1));

        jTextField_MaKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_MaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 480, -1));

        jTextField_TenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_TenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 480, -1));

        jTextField_XepHangThanThiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_XepHangThanThiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 300, 480, -1));

        jTextField_SoTienMuaHangTichLuy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SoTienMuaHangTichLuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 480, -1));

        jButton_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_refresh_100px.png"))); // NOI18N
        jButton_LamMoi.setText("Làm mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 210, 70));

        jButton_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_add_100px.png"))); // NOI18N
        jButton_Them.setText("Thêm khách hàng");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        add(jButton_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 270, 70));

        jButton_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_100px.png"))); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });
        add(jButton_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 220, 70));

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_database_100px.png"))); // NOI18N
        jButton_Xoa.setText("Xóa khách hàng");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 620, 260, 70));

        jButton_ChiTietKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ChiTietKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_more_details_100px.png"))); // NOI18N
        jButton_ChiTietKhachHang.setText("Chi tiết khách hàng");
        jButton_ChiTietKhachHang.setIconTextGap(20);
        jButton_ChiTietKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChiTietKhachHangActionPerformed(evt);
            }
        });
        add(jButton_ChiTietKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 470, 70));

        jButton8.setBackground(new java.awt.Color(51, 153, 255));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 0, 102));
        jButton8.setText("KHÁCH HÀNG");
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 37));

        jTextArea_DiaChi.setColumns(20);
        jTextArea_DiaChi.setRows(5);
        jScrollPane4.setViewportView(jTextArea_DiaChi);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 480, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void getKhachHangList(){
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachKhachHang.getModel();
        ArrayList<KhachHang_DTO> arr = new ArrayList<>();
        arr = khBUS.getAllKhachHangThanThiet();
        for(int i =0;i<arr.size();i++){
            KhachHang_DTO kh = arr.get(i);
            String maKH = kh.getMaKH();
            String tenKH= kh.getTenKH();
            Object[] row = {i+1,maKH,tenKH};
            model.addRow(row);
        }
    }
    
    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachKhachHang.getModel();
        model.setRowCount(0);
        getKhachHangList();
        jTextField_MaKhachHang.setText("");
        jTextField_TenKhachHang.setText("");
        jTextArea_DiaChi.setText("");
        jTextField_XepHangThanThiet.setText("");
        jTextField_SoTienMuaHangTichLuy.setText("");      
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jTable_DanhSachKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachKhachHangMousePressed
        int i = jTable_DanhSachKhachHang.getSelectedRow();
        jTextField_MaKhachHang.setText(jTable_DanhSachKhachHang.getValueAt(i, 1)+"");
        jTextField_TenKhachHang.setText(jTable_DanhSachKhachHang.getValueAt(i, 2)+"");
        ArrayList<KhachHang_DTO> arr = new ArrayList<>();
        arr = khBUS.getAllKhachHangThanThiet();
        for(int k=0;k<arr.size();k++){
            KhachHang_DTO kh = arr.get(k);
            if(kh.getMaKH().equals(jTable_DanhSachKhachHang.getValueAt(i, 1)+"")){
                jTextArea_DiaChi.setText(kh.getDiaChi());
                jTextField_XepHangThanThiet.setText(kh.getXepHang());
                jTextField_SoTienMuaHangTichLuy.setText(kh.getTienHangTichLuy()+"");
            }
        }
    }//GEN-LAST:event_jTable_DanhSachKhachHangMousePressed

    private void jButton_ChiTietKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChiTietKhachHangActionPerformed
        jFrame_ChiTietKhachHang.setTitle("Chi tiết khách hàng");
        jFrame_ChiTietKhachHang.setVisible(true);
        jTextField_CTKH_MaKH.setEditable(false);
        jTextField_CTKH_TenKH.setEditable(false);
        jTextField_CTKH_Sdt.setEditable(false);
        jTextField_CTKH_XepHang.setEditable(false);
        jTextField_CTKH_GioiTinh.setEditable(false);
        jTextField_CTKH_CMND_CCCD.setEditable(false);
        jTextArea_CTKH_DiaChi.setEditable(false);
        DefaultTableModel model = (DefaultTableModel) jTable_CTKH.getModel();
        model.setRowCount(0);
        int i = jTable_DanhSachKhachHang.getSelectedRow();
        jTextField_CTKH_MaKH.setText(jTable_DanhSachKhachHang.getValueAt(i, 1)+"");
        jTextField_CTKH_TenKH.setText(jTable_DanhSachKhachHang.getValueAt(i, 2)+"");
        ArrayList<KhachHang_DTO> arrKH = new ArrayList<>();
        ArrayList<HoaDon_DTO> arrHD = new ArrayList<>();
        arrKH=khBUS.getAllKhachHangThanThiet();
        arrHD=hdBUS.getAllHoaDon();
        for(int k =0;k<arrKH.size();k++){
            KhachHang_DTO kh = arrKH.get(k);
            if(kh.getMaKH().equals(jTable_DanhSachKhachHang.getValueAt(i,1)+"")){
                jTextField_CTKH_Sdt.setText(kh.getSdt()+"");
                jTextField_CTKH_XepHang.setText(kh.getXepHang());
                jTextField_CTKH_GioiTinh.setText(kh.getGioiTinh());
                jTextField_CTKH_CMND_CCCD.setText(kh.getCMND_CCCD()+"");
                jTextArea_CTKH_DiaChi.setText(kh.getDiaChi()+"");
                jTextField_CTKH_TongTienTichLuy.setText(kh.getTienHangTichLuy()+"");
                int stt=0;
                String mahd;
                    String tgtt;
                    double tongTien;
                for(int j =0;j<arrHD.size();j++){
                    HoaDon_DTO hd = arrHD.get(j);
                    
                    if(hd.getId_KhachHang().equals(kh.getMaKH())){
                        stt++;
                        mahd = hd.getID_HoaDon();
                        tgtt = hd.getNgayLap();                        
                        tongTien = hd.getTongTien();
                        Object[] row = {stt,mahd,tgtt,tongTien};
                        model.addRow(row);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton_ChiTietKhachHangActionPerformed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        try{
            if(jTextField_MaKhachHang.getText().trim().equals("")||
                    jTextField_TenKhachHang.getText().trim().equals("")||
                    jTextArea_DiaChi.getText().trim().equals("")||
                    jTextField_XepHangThanThiet.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else{
                KhachHang_DTO khDTO=new KhachHang_DTO();
                khDTO.setMaKH(jTextField_MaKhachHang.getText());
                khDTO.setTenKH(jTextField_TenKhachHang.getText());
                khDTO.setDiaChi(jTextArea_DiaChi.getText());
                khDTO.setXepHang(jTextField_XepHangThanThiet.getText());
                khDTO.setTienHangTichLuy(Double.parseDouble(jTextField_SoTienMuaHangTichLuy.getText()));
                JOptionPane.showMessageDialog(this,khBUS.addkKhachHang(khDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
        
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachKhachHang.getModel();
        model.setRowCount(0);
        ArrayList<KhachHang_DTO> arr = new ArrayList<>();
        arr = khBUS.getAllKhachHangThanThiet();
        for(int i =0;i<arr.size();i++){ 
            KhachHang_DTO kh = arr.get(i);
            if(kh.getMaKH().equalsIgnoreCase(jTextField_MaKhachHang.getText())){
                String makh = kh.getMaKH();
                String hoten = kh.getTenKH();
                Object[] row = {1,makh,hoten};
                model.addRow(row);          
            }           
        }
        if(jTable_DanhSachKhachHang.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng !");
            
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        String str=jTextField_TenKhachHang.getText()+"";
        int a = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa khách hàng '"+str+"' khỏi hệ thống ?" );
        if(a==JOptionPane.YES_OPTION){
                KhachHang_DTO khDTO = new KhachHang_DTO();
                khDTO.setMaKH(jTextField_MaKhachHang.getText());
                JOptionPane.showMessageDialog(this,khBUS.delKhachHang(khDTO));
                jButton_LamMoiActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_CTKH_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CTKH_SuaActionPerformed
        int a = JOptionPane.showConfirmDialog(this,"Bạn có chắc muốn chỉnh sửa thông tin khách hàng ?");
        if(a==JOptionPane.YES_OPTION){            
            jTextField_CTKH_TenKH.setEditable(true);
            jTextField_CTKH_Sdt.setEditable(true);
            jTextField_XepHangThanThiet.setEditable(true);
            jTextField_CTKH_GioiTinh.setEditable(true);
            jTextField_CTKH_CMND_CCCD.setEditable(true);
            jTextArea_DiaChi.setEditable(true);        
        }
    }//GEN-LAST:event_jButton_CTKH_SuaActionPerformed

    private void jButton_CTKH_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CTKH_LuuActionPerformed
        try{
                KhachHang_DTO khDTO=new KhachHang_DTO();
                khDTO.setMaKH(jTextField_CTKH_MaKH.getText());
                khDTO.setTenKH(jTextField_CTKH_TenKH.getText());
                khDTO.setSdt(jTextField_CTKH_Sdt.getText());
                khDTO.setXepHang(jTextField_CTKH_XepHang.getText());
                khDTO.setGioiTinh(jTextField_CTKH_GioiTinh.getText());
                khDTO.setCMND_CCCD(jTextField_CTKH_CMND_CCCD.getText());
                khDTO.setDiaChi(jTextArea_CTKH_DiaChi.getText());
                JOptionPane.showMessageDialog(this,khBUS.editKhachHang(khDTO));
                jFrame_ChiTietKhachHang.dispose();             
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_CTKH_LuuActionPerformed

    private void jFrame_ChiTietKhachHangWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame_ChiTietKhachHangWindowClosing
            jFrame_ChiTietKhachHang.dispose();
    }//GEN-LAST:event_jFrame_ChiTietKhachHangWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton_CTKH_Luu;
    private javax.swing.JButton jButton_CTKH_Sua;
    private javax.swing.JButton jButton_ChiTietKhachHang;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JFrame jFrame_ChiTietKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_CTKH;
    private javax.swing.JTable jTable_DanhSachKhachHang;
    private javax.swing.JTextArea jTextArea_CTKH_DiaChi;
    private javax.swing.JTextArea jTextArea_DiaChi;
    private javax.swing.JTextField jTextField_CTKH_CMND_CCCD;
    private javax.swing.JTextField jTextField_CTKH_GioiTinh;
    private javax.swing.JTextField jTextField_CTKH_MaKH;
    private javax.swing.JTextField jTextField_CTKH_Sdt;
    private javax.swing.JTextField jTextField_CTKH_TenKH;
    private javax.swing.JTextField jTextField_CTKH_TongTienTichLuy;
    private javax.swing.JTextField jTextField_CTKH_XepHang;
    private javax.swing.JTextField jTextField_MaKhachHang;
    private javax.swing.JTextField jTextField_SoTienMuaHangTichLuy;
    private javax.swing.JTextField jTextField_TenKhachHang;
    private javax.swing.JTextField jTextField_XepHangThanThiet;
    // End of variables declaration//GEN-END:variables
}
