package GUI;
import BUS.*;
import DTO.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author trita
 */
public class Panel_Bang_Luong extends javax.swing.JPanel {
    BangLuong_BUS blBUS = new BangLuong_BUS();
    NhanVien_BUS nvBUS = new NhanVien_BUS();
    CuaHang_BUS chBUS = new CuaHang_BUS();
    public String datenow = java.time.LocalDate.now()+"";
    String tmp[] = datenow.split("-");
    String thang = tmp[1];
    String nam = tmp[0];
    
    /**
     * Creates new form Panel_Bang_Luong
     */
    public Panel_Bang_Luong() {
        initComponents();
        getBangLuongList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_LichSuNhanVienDuocLinh = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_LichSuNhanVienDuocLinh = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DanhSachNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Thang = new javax.swing.JComboBox<>();
        jComboBox_Nam = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_HoTen = new javax.swing.JTextField();
        jTextField_ChucVu = new javax.swing.JTextField();
        jTextField_SoNgayCong = new javax.swing.JTextField();
        jTextField_PhuCapAnUong = new javax.swing.JTextField();
        jTextField_PhuCapXang = new javax.swing.JTextField();
        jTextField_TienThuong = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_MoTaTienThuong = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_BaoHiem = new javax.swing.JTextField();
        jTextField_Thue = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField_KhauTruKhac = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_MoTaKhauTru = new javax.swing.JTextArea();
        jLabel_LuongDuocLanh = new javax.swing.JLabel();
        jTextField_LuongDuocLanh = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_TamUng = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel_ThucNhan = new javax.swing.JLabel();
        jLabel_ThoiGianNhan = new javax.swing.JLabel();
        jTextField_LuongThucNhan = new javax.swing.JTextField();
        jButton_LamMoi = new javax.swing.JButton();
        jButton_Sua = new javax.swing.JButton();
        jButton_Them = new javax.swing.JButton();
        jButton_TimKiem = new javax.swing.JButton();
        jButton_Xoa = new javax.swing.JButton();
        jButton_LichSuNhanVien = new javax.swing.JButton();
        jComboBox_CuaHang = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_MaNhanVien = new javax.swing.JComboBox<>();
        jTextField_ThoiGianTamUng = new javax.swing.JTextField();
        jTextField_ThoiGianNhan = new javax.swing.JTextField();

        jFrame_LichSuNhanVienDuocLinh.setMinimumSize(new java.awt.Dimension(1466, 600));
        jFrame_LichSuNhanVienDuocLinh.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jTable_LichSuNhanVienDuocLinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Số ngày công", "Phụ cấp ăn uống", "Phụ cấp xăng", "Tiền thưởng", "Lương cơ bản", "Bảo hiểm", "Thuế", "Khấu trừ khác", "Lương được lĩnh", "Đã tạm ứng", "Thời gian tạm ứng", "Thực nhận", "Thời gian lĩnh"
            }
        ));
        jTable_LichSuNhanVienDuocLinh.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane4.setViewportView(jTable_LichSuNhanVienDuocLinh);

        javax.swing.GroupLayout jFrame_LichSuNhanVienDuocLinhLayout = new javax.swing.GroupLayout(jFrame_LichSuNhanVienDuocLinh.getContentPane());
        jFrame_LichSuNhanVienDuocLinh.getContentPane().setLayout(jFrame_LichSuNhanVienDuocLinhLayout);
        jFrame_LichSuNhanVienDuocLinhLayout.setHorizontalGroup(
            jFrame_LichSuNhanVienDuocLinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_LichSuNhanVienDuocLinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1454, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame_LichSuNhanVienDuocLinhLayout.setVerticalGroup(
            jFrame_LichSuNhanVienDuocLinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_LichSuNhanVienDuocLinhLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        setMinimumSize(new java.awt.Dimension(1350, 688));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("BẢNG LƯƠNG NHÂN VIÊN");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 36));

        jTable_DanhSachNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã NV", "Họ tên"
            }
        ));
        jTable_DanhSachNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_DanhSachNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_DanhSachNhanVienMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_DanhSachNhanVien);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 81, 423, 461));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách nhân viên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tháng");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Năm");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 55, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã nhân viên");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 116, -1));

        jComboBox_Thang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        add(jComboBox_Thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, 63, -1));

        jComboBox_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2023", "2024", "2025" }));
        add(jComboBox_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Họ tên");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 116, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Chức vụ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 116, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số ngày công");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 116, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Phụ cấp ăn uống");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 116, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Phụ cấp xăng");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 116, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tiền thưởng");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 116, -1));
        add(jTextField_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 240, -1));
        add(jTextField_ChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 240, -1));
        add(jTextField_SoNgayCong, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 140, 240, -1));
        add(jTextField_PhuCapAnUong, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 240, -1));
        add(jTextField_PhuCapXang, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 180, 240, -1));
        add(jTextField_TienThuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 240, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mô tả tiền thưởng");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 222, -1, -1));

        jTextArea_MoTaTienThuong.setColumns(20);
        jTextArea_MoTaTienThuong.setRows(5);
        jScrollPane2.setViewportView(jTextArea_MoTaTienThuong);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 240, 52));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Bảo hiểm");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 115, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Thuế");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 292, 116, -1));
        add(jTextField_BaoHiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 240, -1));
        add(jTextField_Thue, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 290, 240, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Khấu trừ khác");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 115, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Mô tả khấu trừ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 332, 116, -1));
        add(jTextField_KhauTruKhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 240, -1));

        jTextArea_MoTaKhauTru.setColumns(20);
        jTextArea_MoTaKhauTru.setRows(5);
        jScrollPane3.setViewportView(jTextArea_MoTaKhauTru);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 330, 240, 61));

        jLabel_LuongDuocLanh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_LuongDuocLanh.setText("Lương được lãnh");
        add(jLabel_LuongDuocLanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 115, -1));
        add(jTextField_LuongDuocLanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 240, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Tạm ứng");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 115, -1));
        add(jTextField_TamUng, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 240, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Thời gian tạm ứng");
        jLabel18.setToolTipText("Thời gian tạm ứng");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 410, 120, -1));

        jLabel_ThucNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ThucNhan.setText("Thực nhận");
        add(jLabel_ThucNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 115, -1));

        jLabel_ThoiGianNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_ThoiGianNhan.setText("Thời gian nhận");
        add(jLabel_ThoiGianNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, -1, -1));

        jTextField_LuongThucNhan.setEditable(false);
        jTextField_LuongThucNhan.setBackground(new java.awt.Color(255, 255, 255));
        add(jTextField_LuongThucNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 240, -1));

        jButton_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_refresh_100px.png"))); // NOI18N
        jButton_LamMoi.setText("Làm mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 208, 60));

        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_edit_100px.png"))); // NOI18N
        jButton_Sua.setText("Sửa");
        jButton_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        add(jButton_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 170, 60));

        jButton_Them.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_add_100px.png"))); // NOI18N
        jButton_Them.setText("Thêm vào bảng lương nhân viên");
        jButton_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ThemActionPerformed(evt);
            }
        });
        add(jButton_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 630, 360, 60));

        jButton_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_search_100px.png"))); // NOI18N
        jButton_TimKiem.setText("Tìm kiếm");
        jButton_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TimKiemActionPerformed(evt);
            }
        });
        add(jButton_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 630, 190, 60));

        jButton_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_delete_database_100px.png"))); // NOI18N
        jButton_Xoa.setText("Xóa");
        jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_XoaActionPerformed(evt);
            }
        });
        add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 160, 60));

        jButton_LichSuNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LichSuNhanVien.setText("Lịch sử nhân viên");
        jButton_LichSuNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LichSuNhanVienActionPerformed(evt);
            }
        });
        add(jButton_LichSuNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 540, 500, 50));

        jComboBox_CuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_CuaHangActionPerformed(evt);
            }
        });
        add(jComboBox_CuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 240, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Chi nhánh");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 116, -1));

        jComboBox_MaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MaNhanVienActionPerformed(evt);
            }
        });
        add(jComboBox_MaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 240, -1));
        add(jTextField_ThoiGianTamUng, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, 240, -1));
        add(jTextField_ThoiGianNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void getBangLuongList(){
        jComboBox_Thang.setSelectedIndex(Integer.parseInt(thang)-1);
        jComboBox_Nam.setSelectedItem(Integer.parseInt(nam)-1);
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachNhanVien.getModel();
        ArrayList<BangLuong_DTO> arrBL = new ArrayList<>();
        ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
        ArrayList<NhanVien_DTO> arrNV = new ArrayList<>();
        arrBL = blBUS.getAllBangLuong();
        arrCH = chBUS.getAllCuaHang();
        arrNV = nvBUS.getAllNhanVien();
        jComboBox_CuaHang.removeAllItems();
        for(int k =0;k<arrCH.size();k++){
            CuaHang_DTO ch = arrCH.get(k);
            jComboBox_CuaHang.addItem(ch.getTenCuaHang());
        }
        int stt=0;
        for(int i =0;i<arrBL.size();i++){
            BangLuong_DTO bl = arrBL.get(i);
            if(bl.getThang()==Integer.parseInt(jComboBox_Thang.getSelectedItem()+"")&&bl.getNam()==Integer.parseInt(jComboBox_Nam.getSelectedItem()+"")){
                String manv = bl.getMaNV();
                String hoten="";
                for(int j =0;j<arrNV.size();j++){
                    NhanVien_DTO nv = arrNV.get(j);
                    if(nv.getMaNV().equals(bl.getMaNV())){
                        hoten=nv.getHoTen();
                    }
                }                     
                Object[] row = {++stt,manv,hoten};
                model.addRow(row);
            }
        }
    }
    
    private void jButton_LichSuNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LichSuNhanVienActionPerformed
        jFrame_LichSuNhanVienDuocLinh.setTitle("Lịch sử nhân viên được lĩnh");
        jFrame_LichSuNhanVienDuocLinh.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) jTable_LichSuNhanVienDuocLinh.getModel();
        ArrayList<BangLuong_DTO> arrBL = new ArrayList<>();
        arrBL = blBUS.getAllBangLuong();
        for(int i =0;i<arrBL.size();i++){
            BangLuong_DTO bl = arrBL.get(i);
            int songaycong = bl.getSoNgayCong();
            double pcanuong = bl.getPhuCapAnUong();
            double pcxang = bl.getPhuCapXang();
            double tienthuong = bl.getTienThuong();
            double luongcoban = bl.getLuongCoBan();
            double baohiem = bl.getBaoHiem();
            double thue = bl.getThue();
            double khautrukhac = bl.getKhauTruKhac();
            double luongduoclinh = bl.getLuongDuocLanh();
            double tamung = bl.getTamUng();
            String thoigiantamung = bl.getThoiGianTamUng()+"";
            double thucnhan = bl.getLuongThucNhan();
            String thoigiannhan = bl.getThoiGianNhan()+"";
            Object[] row = {i+1,songaycong,pcanuong,pcxang,tienthuong,luongcoban,thue,baohiem,khautrukhac,luongduoclinh,tamung,thoigiantamung,thucnhan,thoigiannhan};
            model.addRow(row);
        }
    }//GEN-LAST:event_jButton_LichSuNhanVienActionPerformed

    private void jTable_DanhSachNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_DanhSachNhanVienMousePressed
        int i = jTable_DanhSachNhanVien.getSelectedRow();
        jComboBox_MaNhanVien.removeAllItems();
        jComboBox_CuaHang.removeAllItems();
        ArrayList<BangLuong_DTO> arrBL = new ArrayList<>();
        ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
        ArrayList<NhanVien_DTO> arrNV = new ArrayList<>();
        arrBL= blBUS.getAllBangLuong();
        arrCH= chBUS.getAllCuaHang();
        arrNV= nvBUS.getAllNhanVien();
        for(int k =0;k<arrBL.size();k++){
            BangLuong_DTO bl = arrBL.get(k);
            if(bl.getMaNV().equals(jTable_DanhSachNhanVien.getValueAt(i,1)+"")&&bl.getThang()==Integer.parseInt(jComboBox_Thang.getSelectedItem()+"")&&bl.getNam()==Integer.parseInt(jComboBox_Nam.getSelectedItem()+"")){                
                jComboBox_MaNhanVien.addItem(bl.getMaNV());
                for(int j =0;j<arrNV.size();j++){
                    NhanVien_DTO nv = arrNV.get(j);
                    if(bl.getMaNV().equals(nv.getMaNV())){
                        for(int h =0;h<arrCH.size();h++){
                            CuaHang_DTO ch = arrCH.get(h);
                            if(ch.getMaCH().equals(nv.getMaCH())){
                                jComboBox_CuaHang.addItem(ch.getTenCuaHang());
                            }
                        }
                        jTextField_HoTen.setText(nv.getHoTen());
                        jTextField_ChucVu.setText(nv.getChucVu());                               
                    }                         
                }               
                jTextField_SoNgayCong.setText(bl.getSoNgayCong()+"");
                jTextField_PhuCapAnUong.setText(bl.getPhuCapAnUong()+"");
                jTextField_PhuCapXang.setText(bl.getPhuCapXang()+"");
                jTextField_TienThuong.setText(bl.getTienThuong()+"");
                jTextArea_MoTaTienThuong.setText(bl.getMoTaTienThuong());
                jTextField_BaoHiem.setText(bl.getBaoHiem()+"");
                jTextField_Thue.setText(bl.getThue()+"");
                jTextField_KhauTruKhac.setText(bl.getKhauTruKhac()+"");
                jTextArea_MoTaKhauTru.setText(bl.getMoTaKhauTru());
                jTextField_TamUng.setText(bl.getTamUng()+"");               
                jTextField_ThoiGianTamUng.setText(bl.getThoiGianTamUng()+"");
                jTextField_LuongDuocLanh.setText(bl.getLuongDuocLanh()+"");
                jTextField_LuongThucNhan.setText(bl.getLuongThucNhan()+"");
                jTextField_ThoiGianNhan.setText(bl.getThoiGianNhan()+"");
            }
        }
    }//GEN-LAST:event_jTable_DanhSachNhanVienMousePressed

    private void jButton_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ThemActionPerformed
        try{
            if(jTextField_HoTen.getText().trim().equals("")||
                    jTextField_ChucVu.getText().trim().equals("")||
                    jTextField_SoNgayCong.getText().trim().equals("")
                    )
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            else{
                BangLuong_DTO blDTO = new BangLuong_DTO();
                blDTO.setThang(Integer.parseInt(jComboBox_Thang.getSelectedItem()+""));
                blDTO.setNam(Integer.parseInt(jComboBox_Nam.getSelectedItem()+""));               
                blDTO.setMaNV(jComboBox_MaNhanVien.getSelectedItem()+"");      
                blDTO.setSoNgayCong(Integer.parseInt(jTextField_SoNgayCong.getText()));
                blDTO.setPhuCapAnUong(Double.parseDouble(jTextField_PhuCapAnUong.getText()));
                blDTO.setPhuCapXang(Double.parseDouble(jTextField_PhuCapXang.getText()));
                blDTO.setTienThuong(Double.parseDouble(jTextField_TienThuong.getText()));
                blDTO.setMoTaTienThuong(jTextArea_MoTaTienThuong.getText());
                blDTO.setBaoHiem(Double.parseDouble(jTextField_TienThuong.getText()));
                blDTO.setThue(Double.parseDouble(jTextField_Thue.getText()));
                blDTO.setKhauTruKhac(Double.parseDouble(jTextField_KhauTruKhac.getText()));
                blDTO.setMoTaKhauTru(jTextArea_MoTaKhauTru.getText());
                blDTO.setTamUng(Double.parseDouble(jTextField_TamUng.getText()));
                blDTO.setThoiGianTamUng(jTextField_ThoiGianTamUng.getText());
                blDTO.setLuongDuocLanh();
                blDTO.setLuongThucNhan();                
                blDTO.setThoiGianNhan(jTextField_ThoiGianNhan.getText());
                JOptionPane.showMessageDialog(this,blBUS.addBangLuong(blDTO));
                jButton_LamMoiActionPerformed(evt);
            }
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_jButton_ThemActionPerformed

    private void jButton_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TimKiemActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachNhanVien.getModel();
        model.setRowCount(0);
        ArrayList<NhanVien_DTO> arrNV = new ArrayList<>();
        ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
        arrNV = nvBUS.getAllNhanVien();
        arrCH = chBUS.getAllCuaHang();
        int stt=0;
        for(int i =0;i<arrNV.size();i++){ 
            NhanVien_DTO nv = arrNV.get(i);
            for (int j =0;j<arrCH.size();j++){
                CuaHang_DTO ch = arrCH.get(j);           
                if(nv.getMaCH().equals(ch.getMaCH()) && ch.getTenCuaHang().equals(jComboBox_CuaHang.getSelectedItem()+"")){               
                    String manv = nv.getMaNV();
                    String hoten = nv.getHoTen();
                    stt++;
                    Object[] row = {stt,manv,hoten};
                    model.addRow(row);          
                }
            }           
        }
        if(jTable_DanhSachNhanVien.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên !");
        }
    }//GEN-LAST:event_jButton_TimKiemActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        int i = jTable_DanhSachNhanVien.getSelectedRow();
        int a = JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa dữ liệu bảng lương của nhân viên '"+jTable_DanhSachNhanVien.getValueAt(i, 2)+"' khỏi hệ thống ?" );
        if(a==JOptionPane.YES_OPTION){
            BangLuong_DTO blDTO = new BangLuong_DTO();
            blDTO.setThang(Integer.parseInt(jComboBox_Thang.getSelectedItem()+""));
            blDTO.setNam(Integer.parseInt(jComboBox_Nam.getSelectedItem()+""));
            blDTO.setMaNV(jTable_DanhSachNhanVien.getValueAt(i, 1)+"");
            JOptionPane.showMessageDialog(this,blBUS.delBangLuong(blDTO));
            jButton_LamMoiActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable_DanhSachNhanVien.getModel();
        model.setRowCount(0);
        getBangLuongList();
        jComboBox_MaNhanVien.removeAllItems();
        jTextArea_MoTaKhauTru.setText("");
        jTextArea_MoTaTienThuong.setText("");
        jTextField_BaoHiem.setText("");
        jTextField_ChucVu.setText("");
        jTextField_HoTen.setText("");
        jTextField_KhauTruKhac.setText("");
        jTextField_LuongDuocLanh.setText("");
        jTextField_LuongThucNhan.setText("");
        jTextField_PhuCapAnUong.setText("");
        jTextField_PhuCapXang.setText("");
        jTextField_SoNgayCong.setText("");
        jTextField_TamUng.setText("");
        jTextField_Thue.setText("");
        jTextField_TienThuong.setText("");
        jTextField_ThoiGianTamUng.setText("");
        jTextField_ThoiGianNhan.setText("");
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jComboBox_CuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_CuaHangActionPerformed
        jComboBox_MaNhanVien.removeAllItems();
        ArrayList<NhanVien_DTO> arrNV = new ArrayList<>();
        ArrayList<CuaHang_DTO> arrCH = new ArrayList<>();
        arrNV = nvBUS.getAllNhanVien();
        arrCH = chBUS.getAllCuaHang();
        for(int j =0;j<arrCH.size();j++){
            CuaHang_DTO ch = arrCH.get(j);
            if(ch.getTenCuaHang().equals(jComboBox_CuaHang.getSelectedItem())){
                for(int k =0;k<arrNV.size();k++){
                    NhanVien_DTO nv = arrNV.get(k);
                    if(nv.getMaCH().equals(ch.getMaCH())){
                        jComboBox_MaNhanVien.addItem(nv.getMaNV());
                    }
                } 
            }
        }
    }//GEN-LAST:event_jComboBox_CuaHangActionPerformed

    private void jComboBox_MaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MaNhanVienActionPerformed
        ArrayList<NhanVien_DTO> arrNV = new ArrayList<>();
        arrNV = nvBUS.getAllNhanVien();
        for(int j =0;j<arrNV.size();j++){
            NhanVien_DTO nv = arrNV.get(j);
            if(nv.getMaNV().equals(jComboBox_MaNhanVien.getSelectedItem())){
                jTextField_HoTen.setText(nv.getHoTen());
                jTextField_ChucVu.setText(nv.getChucVu());
            }
        }
    }//GEN-LAST:event_jComboBox_MaNhanVienActionPerformed

    private void jButton_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SuaActionPerformed
        
    }//GEN-LAST:event_jButton_SuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_LichSuNhanVien;
    private javax.swing.JButton jButton_Sua;
    private javax.swing.JButton jButton_Them;
    private javax.swing.JButton jButton_TimKiem;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JComboBox<String> jComboBox_CuaHang;
    private javax.swing.JComboBox<String> jComboBox_MaNhanVien;
    private javax.swing.JComboBox<String> jComboBox_Nam;
    private javax.swing.JComboBox<String> jComboBox_Thang;
    private javax.swing.JFrame jFrame_LichSuNhanVienDuocLinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_LuongDuocLanh;
    private javax.swing.JLabel jLabel_ThoiGianNhan;
    private javax.swing.JLabel jLabel_ThucNhan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_DanhSachNhanVien;
    private javax.swing.JTable jTable_LichSuNhanVienDuocLinh;
    private javax.swing.JTextArea jTextArea_MoTaKhauTru;
    private javax.swing.JTextArea jTextArea_MoTaTienThuong;
    private javax.swing.JTextField jTextField_BaoHiem;
    private javax.swing.JTextField jTextField_ChucVu;
    private javax.swing.JTextField jTextField_HoTen;
    private javax.swing.JTextField jTextField_KhauTruKhac;
    private javax.swing.JTextField jTextField_LuongDuocLanh;
    private javax.swing.JTextField jTextField_LuongThucNhan;
    private javax.swing.JTextField jTextField_PhuCapAnUong;
    private javax.swing.JTextField jTextField_PhuCapXang;
    private javax.swing.JTextField jTextField_SoNgayCong;
    private javax.swing.JTextField jTextField_TamUng;
    private javax.swing.JTextField jTextField_ThoiGianNhan;
    private javax.swing.JTextField jTextField_ThoiGianTamUng;
    private javax.swing.JTextField jTextField_Thue;
    private javax.swing.JTextField jTextField_TienThuong;
    // End of variables declaration//GEN-END:variables
}
