package GUI;

import DTO.*;
import BUS.*;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.time.Month;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author trita
 */
public class Panel_Doanh_Thu extends javax.swing.JPanel {
    DoanhThu_BUS dt_BUS = new DoanhThu_BUS();
    HoaDon_BUS hd_BUS = new HoaDon_BUS();
    ChiTietHoaDon_BUS ct_BUS = new ChiTietHoaDon_BUS();
    CuaHang_BUS ch_BUS = new CuaHang_BUS();
    private ActionEvent event;
    private boolean signal_add_or_update_DoanhThu = true;
    /**
     * Creates new form Panel_Doanh_Thu
     */
    public Panel_Doanh_Thu() {
        initComponents();
        jButton_LamMoiActionPerformed(event);
        reset_tenCH();
        reset_thang();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_CTDT_TheoSanPham = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_DoanhThuTheoSp = new javax.swing.JTable();
        jLabel_TenCH = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField_TongDT_CT_theoSP = new javax.swing.JTextField();
        jLabel_Thang_CT_theoSP = new javax.swing.JLabel();
        jLabel_Nam_CT_theoSP = new javax.swing.JLabel();
        jFrame_CTDT_TheoNhanVien = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel_TenCH_CT_theoNV = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_DoanhThuTheoNV = new javax.swing.JTable();
        jLabel_Thang_CT_theoNV = new javax.swing.JLabel();
        jLabel_Nam_CT_theoNV = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_tongDoanhThu_CT_theoNV = new javax.swing.JTextField();
        jFrame_ChiTietSoTienDaChi = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jFrame_LapDoanhThu = new javax.swing.JFrame();
        jComboBox_Thang_LapDoanhThu = new javax.swing.JComboBox<>();
        jComboBox_Nam_LapDoanhThu = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButton_KiemTra_DT_LapDoanhThu = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton_LapDoanhThu = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBox_CuaHang_LapDoanhThu = new javax.swing.JComboBox<>();
        jLabel_MaNhanVien_LapDoanhThu = new javax.swing.JLabel();
        jLabel_MaNhanVien_LapDoanhThu1 = new javax.swing.JLabel();
        jTextField_TenNhanVien_LapDoanhThu = new javax.swing.JTextField();
        jComboBox_idNhanVien_LapDoanhThu = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jButton_KiemTra_HD_LapDoanhThu = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        javax.swing.JButton jButton_ShowLabel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_DoanhThu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox_Thang = new javax.swing.JComboBox<>();
        jComboBox_Nam = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField_SoLuongBanRa = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton_ChiTietSoTienDaChi = new javax.swing.JButton();
        jButton_CTDT_San_Pham = new javax.swing.JButton();
        jButton_CTDT_Nhan_Vien = new javax.swing.JButton();
        jButton_Lap_doanhThu_thangNay = new javax.swing.JButton();
        jButton_LamMoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox_TenCuaHang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField_DoanhThu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_DoanhThu_Online = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField_DoanhThu_Offline = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField_SoLuong_Online = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_SoLuong_Offline = new javax.swing.JTextField();

        jFrame_CTDT_TheoSanPham.setLocation(new java.awt.Point(200, 100));
        jFrame_CTDT_TheoSanPham.setMinimumSize(new java.awt.Dimension(1103, 600));
        jFrame_CTDT_TheoSanPham.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(1091, 552));

        jTable_DoanhThuTheoSp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên sản phẩm", "Số lượng bán offline", "Doanh thu bán offline", "Số lượng bán online", "Doanh thu bán online", "Tổng số lượng", "Doanh thu"
            }
        ));
        jScrollPane4.setViewportView(jTable_DoanhThuTheoSp);
        if (jTable_DoanhThuTheoSp.getColumnModel().getColumnCount() > 0) {
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(1).setMaxWidth(700);
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(2).setMaxWidth(200);
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(4).setMaxWidth(200);
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(5).setMaxWidth(200);
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(6).setMaxWidth(150);
            jTable_DoanhThuTheoSp.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        jLabel_TenCH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TenCH.setText("Tên chi nhánh");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton5.setBackground(new java.awt.Color(204, 204, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setText("Chú thích: Số lượng ở đây là số lượng sản phẩm bán ra");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Tổng doanh thu");
        jLabel12.setToolTipText("");

        jTextField_TongDT_CT_theoSP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel_Thang_CT_theoSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Thang_CT_theoSP.setText("Tháng");

        jLabel_Nam_CT_theoSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nam_CT_theoSP.setText("Năm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_TenCH, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Thang_CT_theoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_Nam_CT_theoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jButton5)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_TongDT_CT_theoSP, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenCH, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(jButton5)
                    .addComponent(jLabel_Thang_CT_theoSP)
                    .addComponent(jLabel_Nam_CT_theoSP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_TongDT_CT_theoSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jFrame_CTDT_TheoSanPhamLayout = new javax.swing.GroupLayout(jFrame_CTDT_TheoSanPham.getContentPane());
        jFrame_CTDT_TheoSanPham.getContentPane().setLayout(jFrame_CTDT_TheoSanPhamLayout);
        jFrame_CTDT_TheoSanPhamLayout.setHorizontalGroup(
            jFrame_CTDT_TheoSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_CTDT_TheoSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame_CTDT_TheoSanPhamLayout.setVerticalGroup(
            jFrame_CTDT_TheoSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jFrame_CTDT_TheoNhanVien.setLocation(new java.awt.Point(200, 100));
        jFrame_CTDT_TheoNhanVien.setMinimumSize(new java.awt.Dimension(1000, 600));
        jFrame_CTDT_TheoNhanVien.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel2.setMinimumSize(new java.awt.Dimension(971, 570));

        jLabel_TenCH_CT_theoNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TenCH_CT_theoNV.setText("Tên Chi Nhánh");

        jTable_DoanhThuTheoNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã NV", "Tên nhân viên", "Số lượng đơn hàng", "Doanh số"
            }
        ));
        jScrollPane3.setViewportView(jTable_DoanhThuTheoNV);
        if (jTable_DoanhThuTheoNV.getColumnModel().getColumnCount() > 0) {
            jTable_DoanhThuTheoNV.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable_DoanhThuTheoNV.getColumnModel().getColumn(1).setMaxWidth(100);
            jTable_DoanhThuTheoNV.getColumnModel().getColumn(2).setMaxWidth(700);
            jTable_DoanhThuTheoNV.getColumnModel().getColumn(3).setMaxWidth(400);
            jTable_DoanhThuTheoNV.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jLabel_Thang_CT_theoNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Thang_CT_theoNV.setText("Tháng");

        jLabel_Nam_CT_theoNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nam_CT_theoNV.setText("Năm");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tổng doanh thu");

        jTextField_tongDoanhThu_CT_theoNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_TenCH_CT_theoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel_Thang_CT_theoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel_Nam_CT_theoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 649, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jTextField_tongDoanhThu_CT_theoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_TenCH_CT_theoNV)
                    .addComponent(jLabel_Thang_CT_theoNV)
                    .addComponent(jLabel_Nam_CT_theoNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_tongDoanhThu_CT_theoNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jFrame_CTDT_TheoNhanVienLayout = new javax.swing.GroupLayout(jFrame_CTDT_TheoNhanVien.getContentPane());
        jFrame_CTDT_TheoNhanVien.getContentPane().setLayout(jFrame_CTDT_TheoNhanVienLayout);
        jFrame_CTDT_TheoNhanVienLayout.setHorizontalGroup(
            jFrame_CTDT_TheoNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame_CTDT_TheoNhanVienLayout.setVerticalGroup(
            jFrame_CTDT_TheoNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame_ChiTietSoTienDaChi.setMinimumSize(new java.awt.Dimension(1000, 610));
        jFrame_ChiTietSoTienDaChi.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        jPanel3.setMinimumSize(new java.awt.Dimension(953, 591));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("Chi nhánh HCM quận 5");

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Công việc", "Số tiền"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Công việc");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Số tiền");

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("Thêm");

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("Xóa");

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("Sửa");

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setText("Lưu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(126, 126, 126)
                            .addComponent(jButton7)
                            .addGap(101, 101, 101)
                            .addComponent(jButton8)
                            .addGap(124, 124, 124)
                            .addComponent(jButton9)
                            .addGap(135, 135, 135)
                            .addComponent(jButton10))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jFrame_ChiTietSoTienDaChiLayout = new javax.swing.GroupLayout(jFrame_ChiTietSoTienDaChi.getContentPane());
        jFrame_ChiTietSoTienDaChi.getContentPane().setLayout(jFrame_ChiTietSoTienDaChiLayout);
        jFrame_ChiTietSoTienDaChiLayout.setHorizontalGroup(
            jFrame_ChiTietSoTienDaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_ChiTietSoTienDaChiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jFrame_ChiTietSoTienDaChiLayout.setVerticalGroup(
            jFrame_ChiTietSoTienDaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jFrame_LapDoanhThu.setTitle("Lập doanh thu");
        jFrame_LapDoanhThu.setLocation(new java.awt.Point(500, 300));
        jFrame_LapDoanhThu.setMinimumSize(new java.awt.Dimension(770, 350));

        jComboBox_Thang_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jComboBox_Nam_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Năm");

        jButton_KiemTra_DT_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_KiemTra_DT_LapDoanhThu.setText("Kiểm tra");
        jButton_KiemTra_DT_LapDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KiemTra_DT_LapDoanhThuActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Kiểm tra thời gian này đã lập doanh thu chưa?");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Lập doanh thu thời gian này");

        jButton_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LapDoanhThu.setText("Lập");
        jButton_LapDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LapDoanhThuActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cửa hàng");

        jComboBox_CuaHang_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_CuaHang_LapDoanhThu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_CuaHang_LapDoanhThuItemStateChanged(evt);
            }
        });

        jLabel_MaNhanVien_LapDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_MaNhanVien_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_MaNhanVien_LapDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_MaNhanVien_LapDoanhThu.setText("Tên nhân viên");

        jLabel_MaNhanVien_LapDoanhThu1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_MaNhanVien_LapDoanhThu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_MaNhanVien_LapDoanhThu1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_MaNhanVien_LapDoanhThu1.setText("Mã nhân viên");

        jTextField_TenNhanVien_LapDoanhThu.setEditable(false);
        jTextField_TenNhanVien_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jComboBox_idNhanVien_LapDoanhThu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_idNhanVien_LapDoanhThuItemStateChanged(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Tháng");

        jButton_KiemTra_HD_LapDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_KiemTra_HD_LapDoanhThu.setText("Kiểm tra");
        jButton_KiemTra_HD_LapDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KiemTra_HD_LapDoanhThuActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Kiểm tra thời gian này có hóa đơn nào không?");

        javax.swing.GroupLayout jFrame_LapDoanhThuLayout = new javax.swing.GroupLayout(jFrame_LapDoanhThu.getContentPane());
        jFrame_LapDoanhThu.getContentPane().setLayout(jFrame_LapDoanhThuLayout);
        jFrame_LapDoanhThuLayout.setHorizontalGroup(
            jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                        .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                                .addComponent(jLabel_MaNhanVien_LapDoanhThu1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_idNhanVien_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel_MaNhanVien_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TenNhanVien_LapDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                            .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Thang_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_Nam_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_CuaHang_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31))
                    .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                        .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_KiemTra_DT_LapDoanhThu)
                                    .addComponent(jButton_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_KiemTra_HD_LapDoanhThu)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jFrame_LapDoanhThuLayout.setVerticalGroup(
            jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_LapDoanhThuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_Thang_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_Nam_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_CuaHang_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(29, 29, 29)
                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_MaNhanVien_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_MaNhanVien_LapDoanhThu1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TenNhanVien_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_idNhanVien_LapDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jButton_KiemTra_HD_LapDoanhThu))
                .addGap(18, 18, 18)
                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jButton_KiemTra_DT_LapDoanhThu))
                .addGap(18, 18, 18)
                .addGroup(jFrame_LapDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jButton_LapDoanhThu))
                .addGap(39, 39, 39))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_ShowLabel.setBackground(new java.awt.Color(51, 153, 255));
        jButton_ShowLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton_ShowLabel.setForeground(new java.awt.Color(102, 0, 102));
        jButton_ShowLabel.setText("DOANH THU");
        jButton_ShowLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton_ShowLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jButton_ShowLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 37));

        jTable_DoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_DoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Tên cửa hàng", "Tháng", "Năm", "Doanh Thu", "Lợi nhuận"
            }
        ));
        jScrollPane1.setViewportView(jTable_DoanhThu);
        if (jTable_DoanhThu.getColumnModel().getColumnCount() > 0) {
            jTable_DoanhThu.getColumnModel().getColumn(0).setMaxWidth(40);
            jTable_DoanhThu.getColumnModel().getColumn(2).setMaxWidth(70);
            jTable_DoanhThu.getColumnModel().getColumn(3).setMaxWidth(50);
            jTable_DoanhThu.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable_DoanhThu.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 570, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh thu cửa hàng theo tháng");
        jLabel1.setToolTipText("");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 350, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tháng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Năm");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 140, -1, -1));

        jComboBox_Thang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_Thang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_ThangItemStateChanged(evt);
            }
        });
        add(jComboBox_Thang, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 70, -1));

        jComboBox_Nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_Nam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_NamItemStateChanged(evt);
            }
        });
        add(jComboBox_Nam, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số lượng tồn kho");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Số lượng bán ra");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 112, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số tiền đã chi");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 110, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 390, -1));

        jTextField_SoLuongBanRa.setEditable(false);
        jTextField_SoLuongBanRa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SoLuongBanRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 140, -1));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, 390, -1));

        jButton_ChiTietSoTienDaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_ChiTietSoTienDaChi.setText("Chi tiết số tiền đã chi ");
        jButton_ChiTietSoTienDaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ChiTietSoTienDaChiActionPerformed(evt);
            }
        });
        add(jButton_ChiTietSoTienDaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 610, 260, 50));

        jButton_CTDT_San_Pham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_CTDT_San_Pham.setText("Chi tiết doanh thu theo sản phẩm");
        jButton_CTDT_San_Pham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CTDT_San_PhamActionPerformed(evt);
            }
        });
        add(jButton_CTDT_San_Pham, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, 270, 56));

        jButton_CTDT_Nhan_Vien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_CTDT_Nhan_Vien.setText("Chi tiết doanh thu theo nhân viên");
        jButton_CTDT_Nhan_Vien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CTDT_Nhan_VienActionPerformed(evt);
            }
        });
        add(jButton_CTDT_Nhan_Vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 270, 60));

        jButton_Lap_doanhThu_thangNay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Lap_doanhThu_thangNay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_edit_100px.png"))); // NOI18N
        jButton_Lap_doanhThu_thangNay.setText("Lập doanh thu");
        jButton_Lap_doanhThu_thangNay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lap_doanhThu_thangNayActionPerformed(evt);
            }
        });
        add(jButton_Lap_doanhThu_thangNay, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 270, 70));

        jButton_LamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_refresh_100px.png"))); // NOI18N
        jButton_LamMoi.setText("Làm mới");
        jButton_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LamMoiActionPerformed(evt);
            }
        });
        add(jButton_LamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 200, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên cửa hàng");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        jComboBox_TenCuaHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_TenCuaHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_TenCuaHangItemStateChanged(evt);
            }
        });
        add(jComboBox_TenCuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 390, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Doanh thu");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 110, -1));

        jTextField_DoanhThu.setEditable(false);
        jTextField_DoanhThu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_DoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 140, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("ONLINE");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 320, 70, -1));

        jTextField_DoanhThu_Online.setEditable(false);
        jTextField_DoanhThu_Online.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_DoanhThu_Online, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 150, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("OFFLINE");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 70, -1));

        jTextField_DoanhThu_Offline.setEditable(false);
        jTextField_DoanhThu_Offline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_DoanhThu_Offline, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, 150, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("ONLINE");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 240, 70, -1));

        jTextField_SoLuong_Online.setEditable(false);
        jTextField_SoLuong_Online.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SoLuong_Online, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 240, 150, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("OFFLINE");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 70, -1));

        jTextField_SoLuong_Offline.setEditable(false);
        jTextField_SoLuong_Offline.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        add(jTextField_SoLuong_Offline, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 280, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

//=============================================================================================================================================================
//=============================================================================================================================================================
    public void reset_tenCH_LapDT(){
        jComboBox_CuaHang_LapDoanhThu.removeAllItems();
        ArrayList arr_tenCH = ct_BUS.getAll_TenCuaHang();
        for(int i=0; i<arr_tenCH.size(); i++){
            String nameStore = (String) arr_tenCH.get(i);
            jComboBox_CuaHang_LapDoanhThu.addItem(nameStore);
        }
    }
    
    public void reset_tenCH(){
        jComboBox_TenCuaHang.removeAllItems();
        ArrayList arr_tenCH = ct_BUS.getAll_TenCuaHang();
        for(int i=0; i<arr_tenCH.size(); i++){
            String nameStore = (String) arr_tenCH.get(i);
            jComboBox_TenCuaHang.addItem(nameStore);
        }
    }
    
    public void reset_thang_LapDT(){
        jComboBox_Thang_LapDoanhThu.removeAllItems();
        for(int i=1; i<13; i++){
            jComboBox_Thang_LapDoanhThu.addItem(""+i);
        }
    }
    
    public void reset_thang(){
        jComboBox_Thang.removeAllItems();
        for(int i=1; i<13; i++){
            jComboBox_Thang.addItem(""+i);
        }
    }
    
    public void reset_cacNam_LapDT(){
        jComboBox_Nam_LapDoanhThu.removeAllItems();
        ArrayList arr_cacNam = dt_BUS.get_cacNamKeTuNamThanhLap_by_tenCH((String) jComboBox_CuaHang_LapDoanhThu.getSelectedItem());
        for(int i=0; i<arr_cacNam.size(); i++){
            jComboBox_Nam_LapDoanhThu.addItem(""+(int) arr_cacNam.get(i));
        }
    }
    
    public void reset_cacNam(){
        jComboBox_Nam.removeAllItems();
        ArrayList arr_cacNam = dt_BUS.get_cacNamKeTuNamThanhLap_by_tenCH((String) jComboBox_TenCuaHang.getSelectedItem());
        for(int i=0; i<arr_cacNam.size(); i++){
            jComboBox_Nam.addItem(""+(int) arr_cacNam.get(i));
        }
    }
    
    public void reset_idNhanVien_LapDT(){
        jComboBox_idNhanVien_LapDoanhThu.removeAllItems();
        ArrayList arr_idNV = dt_BUS.get_cacIDnhanVien_by_tenCH((String) jComboBox_CuaHang_LapDoanhThu.getSelectedItem());
        for(int i=0; i<arr_idNV.size(); i++){
            jComboBox_idNhanVien_LapDoanhThu.addItem((String) arr_idNV.get(i));
        }
    }
    
    public void reset_info(){
        boolean signal = false;
        if(jComboBox_Thang.getSelectedItem() != null){
            if(jComboBox_Nam.getSelectedItem() != null){
                signal = true;
            }
        }
        if(signal){
            int thang = Integer.parseInt(jComboBox_Thang.getSelectedItem().toString());
            int nam = Integer.parseInt(jComboBox_Nam.getSelectedItem().toString());
            String idCH = hd_BUS.find_id_cuaHang_By_TenCuaHang(jComboBox_TenCuaHang.getSelectedItem().toString());
            DoanhThu_DTO dt = dt_BUS.get_DoanhThu_by_month_year_idCH(thang, nam, idCH);
            jTextField_SoLuongBanRa.setText(dt.getSl_offline()+dt.getSl_online()+"");
            jTextField_SoLuong_Offline.setText(dt.getSl_offline()+"");
            jTextField_SoLuong_Online.setText(dt.getSl_online()+"");
            jTextField_DoanhThu.setText(dt.getTong_doanhThu()+"");
            jTextField_DoanhThu_Offline.setText(dt.getDoanhThu_offline()+"");
            jTextField_DoanhThu_Online.setText(dt.getDoanhThu_online()+"");
        }
    }
    
    public void reset_DoanhThuThangNay(){
        DefaultTableModel model = (DefaultTableModel) jTable_DoanhThu.getModel();
        model.setRowCount(0);
        
        java.util.Date dNow = new java.util.Date();
        SimpleDateFormat ft = new SimpleDateFormat("yyyy");
        SimpleDateFormat ft1 = new SimpleDateFormat("MM");
        String temp = ft.format(dNow);
        int namHienTai = Integer.parseInt(temp);
        temp = ft1.format(dNow);
        int thangHienTai = Integer.parseInt(temp);
        
        ArrayList arr_tenCH = ct_BUS.getAll_TenCuaHang();
        
        int i = 1;
        DoanhThu_DTO dt_ch1 = dt_BUS.get_DoanhThu_by_month_year_idCH(thangHienTai, namHienTai, "CH001");
        Object[] row1 = {i, arr_tenCH.get(0), thangHienTai, namHienTai, dt_ch1.getTong_doanhThu(), dt_ch1.getLoiNhuan()};
        model.addRow(row1);
        
        i += 1;
        DoanhThu_DTO dt_ch2 = dt_BUS.get_DoanhThu_by_month_year_idCH(thangHienTai, namHienTai, "CH002");
        Object[] row2 = {i, arr_tenCH.get(1), thangHienTai, namHienTai, dt_ch2.getTong_doanhThu(), dt_ch2.getLoiNhuan()};
        model.addRow(row2);
        
        i += 1;
        DoanhThu_DTO dt_ch3 = dt_BUS.get_DoanhThu_by_month_year_idCH(thangHienTai, namHienTai, "CH003");
        Object[] row3 = {i, arr_tenCH.get(2), thangHienTai, namHienTai, dt_ch3.getTong_doanhThu(), dt_ch3.getLoiNhuan()};
        model.addRow(row3);
    }
    
    public void reset_doanhThuTheoNV(){
        DefaultTableModel model = (DefaultTableModel) jTable_DoanhThuTheoNV.getModel();
        model.setRowCount(0);
        String tenCH = jComboBox_TenCuaHang.getSelectedItem().toString();
        ArrayList arr_idNV = dt_BUS.get_cacIDnhanVien_by_tenCH(tenCH);
        int thang = Integer.parseInt(jComboBox_Thang.getSelectedItem().toString());
        int nam = Integer.parseInt(jComboBox_Nam.getSelectedItem().toString());
        int tong = 0;
        for(int i=0; i<arr_idNV.size(); i++){
            int stt = i+1;
            String idNV = (String) arr_idNV.get(i);
            String tenNV = hd_BUS.find_TenNV_By_idNV(idNV);
            int sl_donHang = dt_BUS.tinh_SoLuongHD_by_month_year_idNV(thang, nam, idNV, hd_BUS.find_id_cuaHang_By_TenCuaHang(tenCH));    
            int doanhSo = dt_BUS.tinh_doanhSo_by_month_year_idNV(thang, nam, idNV, hd_BUS.find_id_cuaHang_By_TenCuaHang(tenCH));
            tong += doanhSo;
            Object[] row = {stt, idNV, tenNV, sl_donHang, doanhSo};
            model.addRow(row);
        }
        jTextField_tongDoanhThu_CT_theoNV.setText(tong+"");
    }
//=============================================================================================================================================================
//=============================================================================================================================================================
    
    private void jButton_ChiTietSoTienDaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ChiTietSoTienDaChiActionPerformed
        jFrame_ChiTietSoTienDaChi.setTitle("Chi tiết số lượng đã chi");
        jFrame_ChiTietSoTienDaChi.setVisible(true);
    }//GEN-LAST:event_jButton_ChiTietSoTienDaChiActionPerformed

    private void jButton_CTDT_San_PhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CTDT_San_PhamActionPerformed
        jFrame_CTDT_TheoSanPham.setTitle("Chi tiết doanh thu theo sản phẩm");
        jFrame_CTDT_TheoSanPham.setVisible(true);
        
        DefaultTableModel model = (DefaultTableModel) jTable_DoanhThuTheoSp.getModel();
        model.setRowCount(0);
        
        jLabel_TenCH.setText(jComboBox_TenCuaHang.getSelectedItem().toString());
        jLabel_Thang_CT_theoSP.setText("Tháng "+(String) jComboBox_Thang.getSelectedItem());
        jLabel_Nam_CT_theoSP.setText("Năm "+(String) jComboBox_Nam.getSelectedItem());
        int thang = Integer.parseInt(jComboBox_Thang.getSelectedItem().toString());
        int nam = Integer.parseInt(jComboBox_Nam.getSelectedItem().toString());
        int tong = 0;
        ArrayList arr_tenSP = dt_BUS.getAll_tenSP();
        for(int i=0; i<arr_tenSP.size(); i++){
            int stt = i+1;
            String tenSP = (String) arr_tenSP.get(i);
            int sl_off = dt_BUS.tinh_soLuong_by_month_year_tenSP_idCH_moTa(thang, nam, tenSP, hd_BUS.find_id_cuaHang_By_TenCuaHang(jComboBox_TenCuaHang.getSelectedItem().toString()), "OFFLINE");
            int sl_on = dt_BUS.tinh_soLuong_by_month_year_tenSP_idCH_moTa(thang, nam, tenSP, hd_BUS.find_id_cuaHang_By_TenCuaHang(jComboBox_TenCuaHang.getSelectedItem().toString()), "ONLINE");
            int dt_off = dt_BUS.tinh_doanhThu_by_month_year_tenSP_idCH_moTa(thang, nam, tenSP, hd_BUS.find_id_cuaHang_By_TenCuaHang(jComboBox_TenCuaHang.getSelectedItem().toString()), "OFFLINE");
            int dt_on = dt_BUS.tinh_doanhThu_by_month_year_tenSP_idCH_moTa(thang, nam, tenSP, hd_BUS.find_id_cuaHang_By_TenCuaHang(jComboBox_TenCuaHang.getSelectedItem().toString()), "ONLINE");
            int tong_sl = sl_off + sl_on;
            int tong_dt = dt_off + dt_on;
            tong += tong_dt;
            Object[] row = {stt, tenSP, sl_off, dt_off, sl_on, dt_on, tong_sl, tong_dt};
            model.addRow(row);
        }
        jTextField_TongDT_CT_theoSP.setText(tong+"");
    }//GEN-LAST:event_jButton_CTDT_San_PhamActionPerformed

    private void jButton_CTDT_Nhan_VienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CTDT_Nhan_VienActionPerformed
        jFrame_CTDT_TheoNhanVien.setTitle("Chi tiết doanh thu theo nhân viên");
        jFrame_CTDT_TheoNhanVien.setVisible(true);
        jLabel_TenCH_CT_theoNV.setText(jComboBox_TenCuaHang.getSelectedItem().toString());
        jLabel_Thang_CT_theoNV.setText("Tháng "+jComboBox_Thang.getSelectedItem().toString());
        jLabel_Nam_CT_theoNV.setText("Năm "+jComboBox_Nam.getSelectedItem().toString());
        reset_doanhThuTheoNV();
        
    }//GEN-LAST:event_jButton_CTDT_Nhan_VienActionPerformed

    private void jButton_Lap_doanhThu_thangNayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lap_doanhThu_thangNayActionPerformed
        // TODO add your handling code here:
        jFrame_LapDoanhThu.setVisible(true);
        jButton_LapDoanhThu.setEnabled(false);
        reset_thang_LapDT();
        reset_tenCH_LapDT();
    }//GEN-LAST:event_jButton_Lap_doanhThu_thangNayActionPerformed

    private void jButton_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LamMoiActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable_DoanhThu.getModel();
        model.setRowCount(0);
        reset_DoanhThuThangNay();
    }//GEN-LAST:event_jButton_LamMoiActionPerformed

    private void jButton_KiemTra_DT_LapDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KiemTra_DT_LapDoanhThuActionPerformed
        // TODO add your handling code here:
        int thang = Integer.parseInt((String) jComboBox_Thang_LapDoanhThu.getSelectedItem());
        int nam = Integer.parseInt((String) jComboBox_Nam_LapDoanhThu.getSelectedItem());
        String id_CH = hd_BUS.find_id_cuaHang_By_TenCuaHang((String) jComboBox_CuaHang_LapDoanhThu.getSelectedItem());
        if(dt_BUS.is_any_DoanhThu_at_this_time(thang, nam, id_CH)){
            JOptionPane.showMessageDialog(this, "Thời gian này đã lập doanh thu");
        }else{
            if(dt_BUS.is_any_DoanhThu_has_changed_at_this_time(thang, nam, id_CH)){
                JOptionPane.showMessageDialog(this, "Thời gian này doanh thu có sự thay đổi cần lập doanh thu lại");
                signal_add_or_update_DoanhThu = false;
            }else{
                JOptionPane.showMessageDialog(this, "Thời gian này chưa lập doanh thu");
                signal_add_or_update_DoanhThu = true;
            }
            jButton_LapDoanhThu.setEnabled(true);
        }
    }//GEN-LAST:event_jButton_KiemTra_DT_LapDoanhThuActionPerformed

    private void jButton_LapDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LapDoanhThuActionPerformed
        // TODO add your handling code here:
        DoanhThu_DTO dt_dto = new DoanhThu_DTO();
        dt_dto.setId_cuaHang(hd_BUS.find_id_cuaHang_By_TenCuaHang((String) jComboBox_CuaHang_LapDoanhThu.getSelectedItem()));
        dt_dto.setId_NhanVien((String) jComboBox_idNhanVien_LapDoanhThu.getSelectedItem());
        dt_dto.setThang(Integer.parseInt((String) jComboBox_Thang_LapDoanhThu.getSelectedItem()));
        dt_dto.setNam(Integer.parseInt((String) jComboBox_Nam_LapDoanhThu.getSelectedItem()));
        if(signal_add_or_update_DoanhThu){
            if(dt_BUS.add_DoanhThu(dt_dto)){
                JOptionPane.showMessageDialog(this, "Lập doanh thu thành công");
                jButton_LapDoanhThu.setEnabled(false);
                reset_DoanhThuThangNay();
            }else{
                JOptionPane.showMessageDialog(this, "Lập doanh thu thất bại");
            }
        } else {
            // update doanh thu
            if(dt_BUS.update_DoanhThu(dt_dto)){
                JOptionPane.showMessageDialog(this, "Cập nhật doanh thu thành công");
                jButton_LapDoanhThu.setEnabled(false);
                reset_DoanhThuThangNay();
            }else{
                JOptionPane.showMessageDialog(this, "Cập nhật doanh thu thất bại");
            }
        }
        
    }//GEN-LAST:event_jButton_LapDoanhThuActionPerformed

    private void jComboBox_CuaHang_LapDoanhThuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_CuaHang_LapDoanhThuItemStateChanged
        // TODO add your handling code here:
        reset_cacNam_LapDT();
        reset_idNhanVien_LapDT();
    }//GEN-LAST:event_jComboBox_CuaHang_LapDoanhThuItemStateChanged

    private void jComboBox_idNhanVien_LapDoanhThuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_idNhanVien_LapDoanhThuItemStateChanged
        // TODO add your handling code here:
        jTextField_TenNhanVien_LapDoanhThu.setText(hd_BUS.find_TenNV_By_idNV((String) jComboBox_idNhanVien_LapDoanhThu.getSelectedItem()));
    }//GEN-LAST:event_jComboBox_idNhanVien_LapDoanhThuItemStateChanged

    private void jButton_KiemTra_HD_LapDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KiemTra_HD_LapDoanhThuActionPerformed
        // TODO add your handling code here:
        int thang = Integer.parseInt((String) jComboBox_Thang_LapDoanhThu.getSelectedItem());
        int nam = Integer.parseInt((String) jComboBox_Nam_LapDoanhThu.getSelectedItem());
        String id_CH = hd_BUS.find_id_cuaHang_By_TenCuaHang((String) jComboBox_CuaHang_LapDoanhThu.getSelectedItem());
        if(dt_BUS.is_any_HoaDon_at_this_time(thang, nam, id_CH)){
            JOptionPane.showMessageDialog(this, "Thời gian này có hóa đơn");
        }else{
            JOptionPane.showMessageDialog(this, "Thời gian này không có hóa đơn");
        }
    }//GEN-LAST:event_jButton_KiemTra_HD_LapDoanhThuActionPerformed

    private void jComboBox_TenCuaHangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_TenCuaHangItemStateChanged
        // TODO add your handling code here:
        reset_cacNam();
    }//GEN-LAST:event_jComboBox_TenCuaHangItemStateChanged

    private void jComboBox_ThangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_ThangItemStateChanged
        // TODO add your handling code here:
        reset_info();
    }//GEN-LAST:event_jComboBox_ThangItemStateChanged

    private void jComboBox_NamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_NamItemStateChanged
        // TODO add your handling code here:
        reset_info();
    }//GEN-LAST:event_jComboBox_NamItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton_CTDT_Nhan_Vien;
    private javax.swing.JButton jButton_CTDT_San_Pham;
    private javax.swing.JButton jButton_ChiTietSoTienDaChi;
    private javax.swing.JButton jButton_KiemTra_DT_LapDoanhThu;
    private javax.swing.JButton jButton_KiemTra_HD_LapDoanhThu;
    private javax.swing.JButton jButton_LamMoi;
    private javax.swing.JButton jButton_LapDoanhThu;
    private javax.swing.JButton jButton_Lap_doanhThu_thangNay;
    private javax.swing.JComboBox<String> jComboBox_CuaHang_LapDoanhThu;
    private javax.swing.JComboBox<String> jComboBox_Nam;
    private javax.swing.JComboBox<String> jComboBox_Nam_LapDoanhThu;
    private javax.swing.JComboBox<String> jComboBox_TenCuaHang;
    private javax.swing.JComboBox<String> jComboBox_Thang;
    private javax.swing.JComboBox<String> jComboBox_Thang_LapDoanhThu;
    private javax.swing.JComboBox<String> jComboBox_idNhanVien_LapDoanhThu;
    private javax.swing.JFrame jFrame_CTDT_TheoNhanVien;
    private javax.swing.JFrame jFrame_CTDT_TheoSanPham;
    private javax.swing.JFrame jFrame_ChiTietSoTienDaChi;
    private javax.swing.JFrame jFrame_LapDoanhThu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_MaNhanVien_LapDoanhThu;
    private javax.swing.JLabel jLabel_MaNhanVien_LapDoanhThu1;
    private javax.swing.JLabel jLabel_Nam_CT_theoNV;
    private javax.swing.JLabel jLabel_Nam_CT_theoSP;
    private javax.swing.JLabel jLabel_TenCH;
    private javax.swing.JLabel jLabel_TenCH_CT_theoNV;
    private javax.swing.JLabel jLabel_Thang_CT_theoNV;
    private javax.swing.JLabel jLabel_Thang_CT_theoSP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable_DoanhThu;
    private javax.swing.JTable jTable_DoanhThuTheoNV;
    private javax.swing.JTable jTable_DoanhThuTheoSp;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField_DoanhThu;
    private javax.swing.JTextField jTextField_DoanhThu_Offline;
    private javax.swing.JTextField jTextField_DoanhThu_Online;
    private javax.swing.JTextField jTextField_SoLuongBanRa;
    private javax.swing.JTextField jTextField_SoLuong_Offline;
    private javax.swing.JTextField jTextField_SoLuong_Online;
    private javax.swing.JTextField jTextField_TenNhanVien_LapDoanhThu;
    private javax.swing.JTextField jTextField_TongDT_CT_theoSP;
    private javax.swing.JTextField jTextField_tongDoanhThu_CT_theoNV;
    // End of variables declaration//GEN-END:variables
}
