CREATE DATABASE QUAN_LY_CUA_HANG_BAN_QUAN_AO

USE QUAN_LY_CUA_HANG_BAN_QUAN_AO

CREATE TABLE USERS(
	ID INT IDENTITY(1,1),
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(20),
	PRIMARY KEY (USERNAME)
)

CREATE TABLE SAN_PHAM(
	ID_SANPHAM CHAR(5),
	TENSP NVARCHAR(100),
	MOTA NVARCHAR(30),
	THUOCTINH NVARCHAR(30),
	GIA INT,
	ID_NHACUNGCAP CHAR(5),
	PRIMARY KEY (ID_SANPHAM)
)

CREATE TABLE KHO(
	ID_SANPHAM CHAR(5),
	SIZE VARCHAR(10),
	SOLUONG INT,
	THOIGIANCAPNHAT DATE,
	PRIMARY KEY (ID_SANPHAM,SIZE)
)

CREATE TABLE KHACH_HANG(
	ID_KHACHHANG CHAR(5),
	HOTEN NVARCHAR(30),
	DIACHI NVARCHAR(100),
	SDT CHAR(10),
	LOAIKHACHHANG NVARCHAR(30),
	GIOITINH NVARCHAR(5),
	CMND_CCCD NVARCHAR(12),
	PRIMARY KEY (ID_KHACHHANG)
)

CREATE TABLE CUA_HANG(
	ID_CUAHANG CHAR(5),
	TENCUAHANG NVARCHAR(30),
	DIACHI NVARCHAR(100),
	TINHTRANG NVARCHAR(10),
	SDT CHAR(10),
	PRIMARY KEY (ID_CUAHANG)
)

CREATE TABLE NHAN_VIEN(
	ID_NHANVIEN CHAR(5),
	ID_CUAHANG CHAR(5),
	HOTEN NVARCHAR(30),
	DIACHI NVARCHAR(100),
	SDT CHAR(10),
	GIOITINH NVARCHAR(4),
	NGAYSINH DATE,
	CCCD_CMND CHAR(12),
	QUEQUAN NVARCHAR(30),
	HOCVAN NVARCHAR(30),
	KYNANG NVARCHAR(30),
	KINHNGHIEMLAMVIEC NVARCHAR(30),
	CHUCVU NVARCHAR(30),
	LUONGCOBAN DECIMAL(12,2),
	DANHGIACUAKHACHHANG NVARCHAR(30),
	SOLUOTDANHGIA INT,
	PRIMARY KEY (ID_NHANVIEN)
)

CREATE TABLE HOA_DON(
	ID_HOADON CHAR(10),
	ID_CUAHANG CHAR(5),
	NGAYLAP DATETIME,
	ID_NHANVIEN CHAR(5),
	ID_KHACHHANG CHAR(5),
	MOTA NVARCHAR(30),
	PRIMARY KEY (ID_HOADON)
)

CREATE TABLE CHI_TIET_HOA_DON(
	ID_HOADON CHAR(10),
	ID_SANPHAM CHAR(5),
	SOLUONG INT
)

CREATE TABLE BANG_LUONG(
	ID_BANGLUONG INT IDENTITY(1,1),
	ID_NHANVIEN CHAR(5),
	THANG INT,
	NAM INT,
	SONGAYCONG INT,
	PHUCAPANUONG DECIMAL(12,2),
	PHUCAPXANG DECIMAL(12,2),
	TIENTHUONG DECIMAL(12,2),
	MOTATIENTHUONG NVARCHAR(30),
	BAOHIEM DECIMAL(12,2),
	THUE DECIMAL(12,2),
	KHAUTRUKHAC DECIMAL(12,2),
	MOTAKHAUTRU NVARCHAR(30),
	LUONGDUOCLANH DECIMAL(12,2),
	TAMUNG DECIMAL(12,2),
	THOIGIANTAMUNG DATE,
	LUONGTHUCNHAN DECIMAL(12,2),
	THOIGIANNHAN DATE,
	PRIMARY KEY (ID_BANGLUONG)
)

CREATE TABLE HOA_DON_CHI_TRA(
	ID_HOADONCHITRA CHAR(5),
	ID_NHANVIEN CHAR(5),
	ID_CUAHANG CHAR(5),
	NGAYLAP DATETIME,
	MOTA NVARCHAR(30),
	TONGTIEN DECIMAL(12,2)
	PRIMARY KEY (ID_HOADONCHITRA,ID_NHANVIEN, ID_CUAHANG)
)

CREATE TABLE DOANH_THU(
	ID_DOANHTHU INT IDENTITY(1,1),
	ID_NHANVIEN CHAR(5),
	ID_CUAHANG CHAR(5),
	THANG INT,
	NAM INT,
	SOLUONGONLINE INT,
	DOANHTHUONLINE DECIMAL(12,2),
	SOLUONGOFFLINE INT,
	DOANHTHUOFFLINE DECIMAL(12,2),
	TONGDOANHTHU DECIMAL(12,2),
	LOINHUAN DECIMAL(12,2),
	PRIMARY KEY (ID_DOANHTHU)
)

CREATE TABLE NHA_CUNG_CAP(
	ID_NHACUNG CHAR(5),
	TENNHACUNG NVARCHAR(50),
	SDT CHAR(10),
	DIACHI NVARCHAR(100),
	PRIMARY KEY (ID_NHACUNG)
)

CREATE TABLE PHIEU_DAT_HANG(
	ID_PHIEUDAT CHAR(5),
	ID_NHACUNG CHAR(5),
	IDNV_LAPPHIEU CHAR(5),
	NGAYDAT DATETIME,
	PRIMARY KEY (ID_PHIEUDAT)
)

CREATE TABLE CHI_TIET_PHIEU_DAT(
	ID_PHIEUDAT CHAR(5),
	ID_SANPHAM CHAR(5),
	SOLUONG INT
)

CREATE TABLE PHIEU_GIAO_HANG(
	ID_PHIEUGIAO CHAR(5),
	ID_PHIEUDAT CHAR(5),
	IDNV_KIEMTRA CHAR(5),
	ID_NHACUNG CHAR(5),
	NGAYGIAO DATETIME,
	PRIMARY KEY (ID_PHIEUGIAO)
)

CREATE TABLE CHI_TIET_PHIEU_GIAO(
	ID_PHIEUGIAO CHAR(5),
	ID_SANPHAM CHAR(5),
	SOLUONG INT
)

ALTER TABLE KHO
ADD CONSTRAINT FKKHO_SP
FOREIGN KEY (ID_SANPHAM)
REFERENCES SAN_PHAM (ID_SANPHAM)

ALTER TABLE HOA_DON
ADD CONSTRAINT FKHOADON_NHANVIEN
FOREIGN KEY (ID_NHANVIEN)
REFERENCES NHAN_VIEN (ID_NHANVIEN)

ALTER TABLE HOA_DON
ADD CONSTRAINT FKHOADON_KHACHHANG
FOREIGN KEY (ID_KHACHHANG)
REFERENCES KHACH_HANG (ID_KHACHHANG)

ALTER TABLE CHI_TIET_HOA_DON
ADD CONSTRAINT FKHOADON_CHITIETHOADON
FOREIGN KEY (ID_HOADON)
REFERENCES HOA_DON (ID_HOADON)

ALTER TABLE CHI_TIET_HOA_DON
ADD CONSTRAINT FKSANOPHAM_CHITIETHOADON
FOREIGN KEY (ID_SANPHAM)
REFERENCES SAN_PHAM (ID_SANPHAM)

ALTER TABLE BANG_LUONG
ADD CONSTRAINT FKNHANVIEN_BANGLUONG
FOREIGN KEY (ID_NHANVIEN)
REFERENCES NHAN_VIEN (ID_NHANVIEN)

ALTER TABLE HOA_DON_CHI_TRA
ADD CONSTRAINT FKNHANVIEN_HOADONCHITRA
FOREIGN KEY (ID_NHANVIEN)
REFERENCES NHAN_VIEN (ID_NHANVIEN)

ALTER TABLE DOANH_THU
ADD CONSTRAINT FKNHANVIEN_DOANHTHU
FOREIGN KEY (ID_NHANVIEN)
REFERENCES NHAN_VIEN (ID_NHANVIEN)

ALTER TABLE PHIEU_DAT_HANG
ADD CONSTRAINT FKNHANVIEN_PHIEUDATHANG
FOREIGN KEY (IDNV_LAPPHIEU)
REFERENCES NHAN_VIEN (ID_NHANVIEN)

ALTER TABLE PHIEU_DAT_HANG
ADD CONSTRAINT FKNHACUNGCAP_PHIEUDATHANG
FOREIGN KEY (ID_NHACUNG)
REFERENCES NHA_CUNG_CAP (ID_NHACUNG)

ALTER TABLE CHI_TIET_PHIEU_DAT
ADD CONSTRAINT FKPHIEUDATHANG_CHITIETPHIEUDAT
FOREIGN KEY (ID_PHIEUDAT)
REFERENCES PHIEU_DAT_HANG (ID_PHIEUDAT)

ALTER TABLE CHI_TIET_PHIEU_DAT
ADD CONSTRAINT FKSANPHAM_CHITIETPHIEUDAT
FOREIGN KEY (ID_SANPHAM)
REFERENCES SAN_PHAM (ID_SANPHAM)

ALTER TABLE PHIEU_GIAO_HANG
ADD CONSTRAINT FKNHANVIEN_PHIEUGIAOHANG
FOREIGN KEY (IDNV_KIEMTRA)
REFERENCES NHAN_VIEN (ID_NHANVIEN)

ALTER TABLE PHIEU_GIAO_HANG
ADD CONSTRAINT FKNHACUNGCAP_PHIEUGIAOHANG
FOREIGN KEY (ID_NHACUNG)
REFERENCES NHA_CUNG_CAP (ID_NHACUNG)

ALTER TABLE PHIEU_GIAO_HANG
ADD CONSTRAINT FKPHIEUDATHANG_PHIEUGIAOHANG
FOREIGN KEY (ID_PHIEUDAT)
REFERENCES PHIEU_DAT_HANG (ID_PHIEUDAT)

ALTER TABLE SAN_PHAM
ADD CONSTRAINT FKNC_SP
FOREIGN KEY (ID_NHACUNGCAP)
REFERENCES NHA_CUNG_CAP (ID_NHACUNG)

ALTER TABLE CHI_TIET_PHIEU_GIAO
ADD CONSTRAINT FKPHIEUGIAOHANG_CHITIETPHIEUGIAO
FOREIGN KEY (ID_PHIEUGIAO)
REFERENCES PHIEU_GIAO_HANG (ID_PHIEUGIAO)

ALTER TABLE CHI_TIET_PHIEU_GIAO
ADD CONSTRAINT FKSANPHAM_CHITIETPHIEUGIAO
FOREIGN KEY (ID_SANPHAM)
REFERENCES SAN_PHAM (ID_SANPHAM)

ALTER TABLE HOA_DON
ADD CONSTRAINT FKCUAHANG_HOADON
FOREIGN KEY (ID_CUAHANG)
REFERENCES CUA_HANG (ID_CUAHANG)

ALTER TABLE HOA_DON_CHI_TRA
ADD CONSTRAINT FKCUAHANG_HOADONCHITRA
FOREIGN KEY (ID_CUAHANG)
REFERENCES CUA_HANG (ID_CUAHANG)

ALTER TABLE DOANH_THU
ADD CONSTRAINT FKCUAHANG_DOANHTHU
FOREIGN KEY (ID_CUAHANG)
REFERENCES CUA_HANG (ID_CUAHANG)

ALTER TABLE NHAN_VIEN
ADD CONSTRAINT FKCUAHANG_NHANVIEN
FOREIGN KEY (ID_CUAHANG)
REFERENCES CUA_HANG (ID_CUAHANG)


--Liệt kê các sản phẩm cần phải đặt
SELECT SP.ID_SANPHAM, SP.TENSP, K.SIZE, K.SOLUONG
FROM KHO K, SAN_PHAM SP
WHERE K.ID_SANPHAM = SP.ID_SANPHAM
AND MONTH(K.THOIGIANCAPNHAT) = 5 
AND YEAR(K.THOIGIANCAPNHAT) = 2022
AND K.SOLUONG<20

--San pham ban chay nhat
SELECT SP1.ID_SANPHAM, SP1.TENSP, SUM(CTHD1.SOLUONG)
FROM HOA_DON HD1, CHI_TIET_HOA_DON CTHD1, SAN_PHAM SP1
WHERE HD1.ID_HOADON = CTHD1.ID_HOADON AND SP1.ID_SANPHAM = CTHD1.ID_SANPHAM
AND MONTH(HD1.NGAYLAP) = 2 AND YEAR(HD1.NGAYLAP) = 2022
GROUP BY CTHD1.ID_SANPHAM,SP1.ID_SANPHAM, SP1.TENSP
HAVING SUM(CTHD1.SOLUONG) >=ALL
(
	SELECT SUM(CTHD2.SOLUONG)
	FROM HOA_DON HD2, CHI_TIET_HOA_DON CTHD2, SAN_PHAM SP2
	WHERE HD2.ID_HOADON = CTHD2.ID_HOADON AND SP2.ID_SANPHAM = CTHD2.ID_SANPHAM
	AND MONTH(HD2.NGAYLAP) = 2 AND YEAR(HD2.NGAYLAP) = 2022
	GROUP BY CTHD2.ID_SANPHAM,SP2.ID_SANPHAM
)

--Cua hang co doanh thu cao nhat
SELECT CH.ID_CUAHANG, CH.TENCUAHANG, DT.LOINHUAN
FROM CUA_HANG CH, DOANH_THU DT
WHERE CH.ID_CUAHANG = DT.ID_CUAHANG AND DT.LOINHUAN = 
(
	SELECT MAX(DT1.LOINHUAN) 
	FROM CUA_HANG CH1,DOANH_THU DT1
	WHERE CH1.ID_CUAHANG = DT.ID_CUAHANG AND DT.THANG = 5 AND DT.NAM = 2022
)

--Nhan vien co doanh so cao nhat
SELECT NV.ID_NHANVIEN, NV.HOTEN, CH.TENCUAHANG, SUM(SP.GIA*CTHD.SOLUONG)
FROM NHAN_VIEN NV, HOA_DON HD, CUA_HANG CH, CHI_TIET_HOA_DON CTHD, SAN_PHAM SP
WHERE NV.ID_NHANVIEN = HD.ID_NHANVIEN AND CH.ID_CUAHANG = NV.ID_CUAHANG
AND CTHD.ID_HOADON = HD.ID_HOADON AND SP.ID_SANPHAM = CTHD.ID_SANPHAM
AND MONTH(HD.NGAYLAP)= 5 AND YEAR(HD.NGAYLAP)=2022
GROUP BY CTHD.ID_HOADON, NV.ID_NHANVIEN,NV.HOTEN, CH.TENCUAHANG
HAVING SUM(SP.GIA*CTHD.SOLUONG) >= ALL
(
	SELECT SUM(SP1.GIA*CTHD1.SOLUONG)
	FROM NHAN_VIEN NV1, HOA_DON HD1, CUA_HANG CH1, CHI_TIET_HOA_DON CTHD1, SAN_PHAM SP1
	WHERE NV1.ID_NHANVIEN = HD1.ID_NHANVIEN AND CH1.ID_CUAHANG = NV1.ID_CUAHANG
	AND CTHD1.ID_HOADON = HD1.ID_HOADON AND SP1.ID_SANPHAM = CTHD1.ID_SANPHAM
	AND MONTH(HD1.NGAYLAP)= 5 AND YEAR(HD1.NGAYLAP)=2022
	GROUP BY CTHD1.ID_HOADON
)